"""Pack the keg-opening troll flipbook (from the owner's Gwent Beta 0.9.24 recording) into art pages 21+.

Source: frames111/001..048.png (640x840 moving crop, 24 fps), scene111.png (1440x810) and src/bg.png
(blurred final frame, background of the reveal screen). Pages: 2 x 3 frames (1280x2520).
Registers ids -2400..-2447 (frames), -2490 (scene) and -2240 (background) in BetaGwentHDArt.as and writes
BetaGwentKeg109.as. Pages 21+ are embedded only in the keg menu (tools/ui/build_board.py page filter).
Run: python tools/ui/build_keg109.py
"""
from pathlib import Path
import json,re,sys
from PIL import Image
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/'BetaGwent/ui/assets/keg109/src';OUT=ROOT/'BetaGwent/ui/assets/keg109'
FIRST_PAGE=21;W,H=640,840  # Moving crop, plus a separate 1440x810 scene; native budget checked by installer.
def main():
    # Stage 111: 48 frames taken directly from the 2560x1440 recording at 24 fps.
    frames=sorted((SRC/'frames111').glob('*.png'));items=[(-2400-i,Image.open(f).convert('RGB')) for i,f in enumerate(frames)]
    slots={};pages=[]
    for start in range(0,len(items),6):
        chunk=items[start:start+6];rows=(len(chunk)+1)//2
        page=Image.new('RGB',(2*W,rows*H));index=FIRST_PAGE+len(pages)
        for k,(ident,im) in enumerate(chunk):
            im=im.resize((W,H));x,y=(k%2)*W,(k//2)*H;page.paste(im,(x,y));slots[str(ident)]=[index,x,y,W,H]
        name='keg109-%d.png'%len(pages);page.save(OUT/name);pages.append(name)
    scene=Image.open(SRC/'scene111.png').convert('RGB');index=FIRST_PAGE+len(pages)
    scene.save(OUT/'keg109-scene.png');slots['-2490']=[index,0,0,scene.width,scene.height];pages.append('keg109-scene.png')
    # Blurred reveal background: its own small page (blur hides the lower resolution).
    bg=Image.open(SRC/'bg.png').convert('RGB');index=FIRST_PAGE+len(pages)
    bg.save(OUT/'keg109-bg.png');slots['-2240']=[index,0,0,bg.width,bg.height];pages.append('keg109-bg.png')
    # Stage 110: the mod's own faction backs (build_hud104.faction_back: tinted Neutral_SmallCardMesh_CardBack
    # with a small gold faction emblem) at full texture resolution 364x460 instead of the 128x171 HUD copy.
    # Order = editorFactionIndex: monsters, nilfgaard, northern, scoiatael, skellige, neutral.
    import build_hud104 as HB
    base=Image.open(OUT/'backs'/'Neutral_raw.png').convert('RGBA')
    # Read full 256px emblems, never the 64px battle HUD copies. Same atlas size/budget.
    sys.path.insert(0,str(ROOT/'tools/vendor/audio-python'))
    import UnityPy
    unity=UnityPy.load(str(ROOT/'Gwent 0.9.24.3.432/Gwent_Data/sharedassets8.assets'))
    objects={o.path_id:o for o in unity.objects}
    original_emblems=[objects[pid].read().image.convert('RGBA') for pid in (533,546,512,758,592)]
    hd=json.loads(re.search(r'private static var slots:Object=(\{.*?\});',(ROOT/'BetaGwent/ui/src/BetaGwentHDArt.as').read_text('utf-8-sig'))[1])
    backs=Image.new('RGB',(3*364,2*460));index=FIRST_PAGE+len(pages)
    for k,f in enumerate(HB.FACTIONS):
        em=None
        if k<5:em=original_emblems[k]
        im=(HB.faction_back(base,em,HB.BACK_TINT[f]) if HB.BACK_TINT[f] else base.crop((28,28,392,488))).convert('RGB');x,y=(k%3)*364,(k//3)*460
        backs.paste(im,(x,y));slots[str(-2250-k)]=[index,x,y,364,460]
    backs.save(OUT/'keg109-backs.png');pages.append('keg109-backs.png')
    src=ROOT/'BetaGwent/ui/src/BetaGwentHDArt.as';raw=src.read_bytes();bom=raw.startswith(b'\xef\xbb\xbf')
    crlf=b'\r\n' in raw;text=raw.decode('utf-8-sig').replace('\r\n','\n')
    m=re.search(r'private static var slots:Object=(\{.*?\});',text)
    binding={k:v for k,v in json.loads(m[1]).items() if v[0]<FIRST_PAGE};binding.update(slots)
    text=text[:m.start(1)]+json.dumps(binding,separators=(',',':'))+text[m.end(1):]
    text=re.sub(r' \[Embed\(source="\.\./assets/keg109/[^\n]*\n','',text)
    embeds=''.join(' [Embed(source="../assets/keg109/%s",compression="true",quality="100")] private static var Page%d:Class;\n'%(n,FIRST_PAGE+i) for i,n in enumerate(pages))
    text=text.replace(' private static var types:Array=',embeds+' private static var types:Array=')
    text=re.sub(r'private static var types:Array=\[[^\]]*\]','private static var types:Array=['+','.join('Page%d'%i for i in range(FIRST_PAGE+len(pages)))+']',text)
    src.write_bytes((b'\xef\xbb\xbf' if bom else b'')+(text.replace('\n','\r\n') if crlf else text).encode('utf8'))
    (ROOT/'BetaGwent/ui/src/BetaGwentKeg109.as').write_text('''package {
    // GENERATED by tools/ui/build_keg109.py: keg-opening troll flipbook (art pages %d..%d, keg menu only).
    public class BetaGwentKeg109 {
        public static const FRAME0:int=-2400, FRAMES:int=%d, FPS:int=24, SCENE:int=-2490, SMASH_FRAME:int=40, BACKGROUND:int=-2240, BACK0:int=-2250;
        public static const PATCH_X:Number=548.5714286, PATCH_Y:Number=0, PATCH_W:Number=822.8571429, PATCH_H:Number=1080;
        public static const FIRST_PAGE:int=%d, LAST_PAGE:int=%d;
    }
}
'''%(FIRST_PAGE,FIRST_PAGE+len(pages)-1,len(frames),FIRST_PAGE,FIRST_PAGE+len(pages)-1),'utf8')
    print('pages',pages,'frames',len(frames))
if __name__=='__main__':main()
