"""HD leader covers for the deck-selection screen (art page 20, opaque -> BC1).

The selection frame is 625x440; the old cover was a crop of the 288x405 compact card
face (2.2x upscale). Covers here come straight from the source illustration crop
(about 497 px wide), packed at 432x304. Ids: -2100 - index; generated
BetaGwentCovers107.as maps leader templateId -> id.
"""
from pathlib import Path
import hashlib, json, re
from PIL import Image
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'BetaGwent/ui/assets/battle107/covers107.png'
LEADERS = [131101, 200055, 200158, 200159, 200160, 200161, 200162, 200163, 200164, 200165, 200166,
           200167, 200168, 200169, 200170, 201580, 201587, 201589, 201595, 201597, 201743]
W, H, PAGE, COLS = 432, 304, 20, 3

def main():
    cards = {c['templateId']: c for c in json.loads((ROOT / 'docs/evidence/card-art-build.json').read_text('utf8'))['cards']}
    page = Image.new('RGB', (W * COLS, H * ((len(LEADERS) + COLS - 1) // COLS)), (16, 14, 12))
    slots = {}; ids = {}
    for i, leader in enumerate(LEADERS):
        c = cards.get(leader)
        if not c: print('no art for', leader); continue
        source = Path(c['source'])
        if not source.exists(): source = ROOT / c['source'].replace('\\', '/').split('w3mod/', 1)[-1]
        art = Image.open(source).convert('RGB').crop(tuple(c['crop']))
        cw = art.width; ch = min(art.height, round(cw * 440 / 625)); top = round((art.height - ch) * 0.2)
        cover = art.crop((0, top, cw, top + ch)).resize((W, H), Image.Resampling.LANCZOS)
        x, y = (i % COLS) * W, (i // COLS) * H
        page.paste(cover, (x, y)); ident = -2100 - i
        slots[str(ident)] = [PAGE, x, y, W, H]; ids[leader] = ident
    OUT.parent.mkdir(parents=True, exist_ok=True); page.save(OUT)
    src = ROOT / 'BetaGwent/ui/src/BetaGwentHDArt.as'; raw = src.read_bytes(); bom = raw.startswith(b'\xef\xbb\xbf')
    crlf = b'\r\n' in raw; text = raw.decode('utf-8-sig').replace('\r\n', '\n')
    m = re.search(r'private static var slots:Object=(\{.*?\});', text)
    binding = {k: v for k, v in json.loads(m[1]).items() if v[0] != PAGE}
    if set(binding) & set(slots): raise SystemExit('atlas id clash')
    binding.update(slots)
    text = text[:m.start(1)] + json.dumps(binding, separators=(',', ':')) + text[m.end(1):]
    if 'private static var Page20:Class' not in text:
        text = text.replace(' private static var types:Array=', ' [Embed(source="../assets/battle107/covers107.png",compression="true",quality="100")] private static var Page20:Class;\n private static var types:Array=')
        text = text.replace('Page18,Page19];', 'Page18,Page19,Page20];')
    if 'Page19,Page20' not in text: raise SystemExit('BetaGwentHDArt.as layout changed')
    src.write_bytes((b'\xef\xbb\xbf' if bom else b'') + (text.replace('\n', '\r\n') if crlf else text).encode('utf8'))
    (ROOT / 'BetaGwent/ui/src/BetaGwentCovers107.as').write_text('''package {
    // GENERATED by tools/ui/build_covers107.py: HD leader covers (art page 20).
    public class BetaGwentCovers107 {
        private static const IDS:Object={%s};
        public static function cover(leader:int):int{return IDS[leader]!=null?int(IDS[leader]):0;}
    }
}
''' % ','.join('%d:%d' % kv for kv in ids.items()), 'utf8')
    print('page 20:', page.size, len(ids), 'covers')

if __name__ == '__main__':
    main()
