package {
    // GENERATED by tools/ui/build_keg109.py: keg-opening troll flipbook (art pages 21..31, keg menu only).
    public class BetaGwentKeg109 {
        public static const FRAME0:int=-2400, FRAMES:int=48, FPS:int=24, SCENE:int=-2490, SMASH_FRAME:int=40, BACKGROUND:int=-2240, BACK0:int=-2250;
        public static const PATCH_X:Number=548.5714286, PATCH_Y:Number=0, PATCH_W:Number=822.8571429, PATCH_H:Number=1080;
        public static const FIRST_PAGE:int=21, LAST_PAGE:int=31;
    }
}
