package {
    // GENERATED by tools/ui/build_hud104.py: original Gwent Beta HUD sprite ids (art page 15).
    public class BetaGwentHud104 {
        public static const PLAYER_AVATAR:int=-1700;
        private static const LEADER_AVATARS:Object={131101:-1718,200055:-1708,200158:-1716,200159:-1714,200160:-1702,200161:-1705,200162:-1704,200163:-1710,200164:-1701,200165:-1720,200166:-1703,200167:-1715,200168:-1719,200169:-1707,200170:-1706,201580:-1710,201587:-1709,201589:-1712,201595:-1711,201597:-1713,201743:-1709};
        private static const FACTION_AVATARS:Array=[-1709,-1710,-1711,-1712,-1713,-1717];
        public static function avatar(leader:int,faction:int):int{return LEADER_AVATARS[leader]!=null?int(LEADER_AVATARS[leader]):int(FACTION_AVATARS[Math.max(0,Math.min(5,faction))]);}
        public static function titleBg(faction:int):int{return -1740-Math.max(0,Math.min(5,faction));}
        public static function infoBg(faction:int):int{return -1750-Math.max(0,Math.min(5,faction));}
        public static function titleLine(faction:int):int{return -1760-Math.max(0,Math.min(5,faction));}
        public static function cardBack(faction:int):int{return -1830-Math.max(0,Math.min(5,faction));}
        public static const TURN_BG:int=-1730,TURN_LEFT:int=-1731,TURN_RIGHT:int=-1732,STATUS_SHADOW:int=-1733,GRADIENT:int=-1734;
        public static const POPUP_TITLE:int=-1770,MENU_IDLE:int=-1780,MENU_HOVER:int=-1781,WIDE_IDLE:int=-1782,WIDE_HOVER:int=-1783;
        public static const KEY_LC:int=-1790,KEY_RC:int=-1791,PAD_A:int=-1792,PAD_B:int=-1793,PAD_X:int=-1794,PAD_Y:int=-1795,
            PAD_LB:int=-1796,PAD_RB:int=-1797,PAD_LT:int=-1798,PAD_RT:int=-1799,PAD_BACK:int=-1800,PAD_START:int=-1801,PAD_RS:int=-1802;
        public static const SHIELD:int=-1810,TIMER:int=-1811,CROWN_EMPTY:int=-1815,CROWN_LEFT_BLUE:int=-1816,CROWN_RIGHT_BLUE:int=-1817,
            CROWN_LEFT_RED:int=-1818,CROWN_RIGHT_RED:int=-1819,ROW_ARROW:int=-1825;
        public static function introLeft(faction:int):int{return -1870-Math.max(0,Math.min(4,faction));}
        public static function introRight(faction:int):int{return -1875-Math.max(0,Math.min(4,faction));}
        public static const VS:int=-1880;
        public static const PARCHMENT:int=-1850,WOOD_PANEL:int=-1851,PREVIEW_SLOT:int=-1852,CHAIN:int=-1853,POPUP:int=-1854;
    }
}
