package {
    import flash.text.Font;
    import flash.text.TextField;
    import flash.text.TextFormat;
    // GENERATED by tools/ui/build_beta_fonts104.py: original Gwent Beta 0.9.24 fonts.
    public class BetaGwentFonts {
        public static const BODY:String="PF Din Text Cond Pro";
        public static const TITLE:String="Halis GR";
        public static const NUMBERS:String="Gwent Numbers";
        private static const BODY_CHARS:Array=[32,125,161,161,163,163,165,165,169,171,174,174,176,176,183,183,186,187,191,196,199,207,209,220,223,228,231,239,241,246,248,252,260,263,280,281,321,324,338,339,346,347,377,380,1025,1025,1028,1028,1030,1030,1040,1103,1105,1105,1108,1108,1110,1110,8211,8212,8217,8217,8220,8222,8230,8230,8364,8364,8470,8470,8482,8482,8592,8595,8722,8722,9633,9633,9651,9651,9675,9675];
        private static const TITLE_CHARS:Array=[32,125,161,161,163,163,165,165,169,171,174,174,176,176,183,183,186,187,191,196,199,207,209,220,223,228,231,239,241,246,248,252,260,263,280,281,321,324,338,339,346,347,377,380,1025,1025,1028,1028,1030,1030,1040,1103,1105,1105,1108,1108,1110,1110,8211,8212,8217,8217,8220,8222,8230,8230,8364,8364,8482,8482,8592,8595,8722,8722,9633,9633,9651,9651,9675,9675];
        private static const NUMBER_CHARS:Array=[48,57];
        private static var checked:Boolean=false;
        public static var available:Boolean=false;
        public static function init():Boolean
        {
            if(checked)return available;checked=true;
            try{
                Font.registerFont(BetaFontHalisMedium);Font.registerFont(BetaFontHalisBold);
                Font.registerFont(BetaFontDin);Font.registerFont(BetaFontNumbers);
                for each(var f:Font in Font.enumerateFonts(false))if(f.fontName==BODY)available=true;
            }catch(e:Error){available=false;}
            return available;
        }
        public static function supports(face:String,value:String):Boolean
        {
            if(!init()||value==null)return false;
            var set:Array=face==NUMBERS?NUMBER_CHARS:face==TITLE?TITLE_CHARS:BODY_CHARS;
            for(var i:int=0;i<value.length;i++){
                var c:int=value.charCodeAt(i);if(c==10||c==13)continue;
                var found:Boolean=false;for(var r:int=0;r<set.length;r+=2)if(c>=set[r]&&c<=set[r+1]){found=true;break;}
                if(!found)return false;
            }
            return true;
        }
        // Apply a Beta face when every character exists in it; otherwise keep the game font.
        public static function apply(field:TextField,face:String,size:Number,color:uint,bold:Boolean=false,align:String=null,spacing:Number=0):Boolean
        {
            var beta:Boolean=supports(face,field.text);
            var format:TextFormat=new TextFormat(beta?face:"$NormalFont",size,color,bold&&(!beta||face==TITLE),null,null,null,null,align);
            if(beta&&spacing!=0)format.letterSpacing=spacing;
            field.embedFonts=beta;field.defaultTextFormat=format;field.setTextFormat(format);
            return beta;
        }
    }
}
