package {
    // GENERATED by tools/ui/build_covers107.py: HD leader covers (art page 20).
    public class BetaGwentCovers107 {
        private static const IDS:Object={131101:-2100,200055:-2101,200158:-2102,200159:-2103,200160:-2104,200161:-2105,200162:-2106,200163:-2107,200164:-2108,200165:-2109,200166:-2110,200167:-2111,200168:-2112,200169:-2113,200170:-2114,201580:-2115,201587:-2116,201589:-2117,201595:-2118,201597:-2119,201743:-2120};
        public static function cover(leader:int):int{return IDS[leader]!=null?int(IDS[leader]):0;}
    }
}
