package {
    // GENERATED by tools/ui/build_weather107.py: original Beta row-weather layers (art page 19).
    public class BetaGwentWeather107 {
        public static const FROST_COVER:int=-1950,
            FROST_SPIKES:int=-1951,
            FROST_RIM:int=-1952,
            FOG_BODY:int=-1953,
            RAIN_WET:int=-1954,
            RAIN_DROPS:int=-1955,
            DROUGHT_CRACKS:int=-1956,
            DROUGHT_SAND:int=-1957,
            RAGH_ROCKS:int=-1958,
            RAGH_VEINS:int=-1959,
            STORM_SEA:int=-1960,
            MOON:int=-1962,
            FROTH_FOAM:int=-1963,
            PITFALL_WOOD:int=-1964,
            DREAM_HEAD:int=-1965,
            SPARKLE:int=-1966,
            NOVA:int=-1967,
            TOKEN_SPYING:int=-1968,
            TOKEN_VISIBILITY:int=-1969;
    }
}
