package {
    // GENERATED by tools/ui/extract_beta_layout103.py from Gwent Beta 0.9.24 level8.
    // Original perspective camera projected to 1920x1080. Values: [x, y, width, height].
    public class BetaGwentBoardLayout {
        public static const boardHalf:Object={"1":[156.0,524.9,1427.0,492.4],"2":[156.0,62.6,1427.0,492.4]};
        public static const rows:Object={"1:1":[526.4,561.4,904.5,118.1],"1:2":[526.4,681.4,904.5,118.1],"1:4":[526.4,802.5,904.5,118.1],"2:1":[526.4,400.6,904.5,118.1],"2:2":[526.4,280.5,904.5,118.1],"2:4":[526.4,159.4,904.5,118.1]};
        public static const rowScore:Object={"1:1":[433.8,592.7,66.9,56.6],"1:2":[439.0,710.6,56.6,61.7],"1:4":[433.8,832.8,66.9,56.6],"2:1":[433.8,429.2,66.9,56.6],"2:2":[439.0,308.1,56.6,61.7],"2:4":[433.8,190.1,66.9,56.6]};
        public static const crownHalf:Object={"1:1":[158.3,697.0,60.1,91.4],"1:2":[199.2,697.0,60.1,91.4],"2:1":[158.3,291.6,60.1,91.4],"2:2":[199.2,291.6,60.1,91.4]};
        public static const score:Object={"1":[269.3,686.0,123.4,113.5],"2":[269.3,280.5,123.4,113.5]};
        public static const handCounter:Object={"1":[424.6,964.6,62.4,54.7],"2":[424.6,55.2,62.4,54.7]};
        public static const handCount:Object={"1":[416.1,994.5,79.5,34.8],"2":[416.1,40.3,79.5,34.8]};
        public static const deck:Object={"1":[1701.5,926.1,125.1,148.9],"2":[1701.5,5.0,125.1,148.9]};
        public static const grave:Object={"1":[1575.1,926.1,125.1,148.9],"2":[1575.1,5.0,125.1,148.9]};
        public static const leader:Object={"1":[501.8,912.5,146.2,200.2],"2":[501.8,-32.7,146.2,200.2]};
        public static const hand:Object={"1":[645.5,910.2,787.7,204.8],"2":[645.5,-35.0,787.7,204.8]};
        public static const presentation:Object={"1":[1358.5,629.1,152.8,212.2],"2":[1358.5,238.7,152.8,212.2]};
        public static const ribbon:Object={"0:1":[28.6,683.5,381.6,119.5],"0:2":[28.6,277.0,381.6,119.5],"1:1":[28.7,680.7,390.7,126.5],"1:2":[28.7,270.9,390.7,129.1],"2:1":[28.3,682.9,392.5,120.0],"2:2":[28.3,277.1,392.5,120.0],"3:1":[28.5,683.6,391.6,119.3],"3:2":[28.5,276.7,391.6,119.3],"4:1":[28.9,683.8,372.0,119.2],"4:2":[28.9,276.8,372.0,119.2]};
        public static const coin:Array=[145.8,479.3,126.4,122.2];
        public static const passButton:Array=[117.5,459.7,172.7,160.6];
        public static function rect(table:Object,key:String):Array { return table[key] as Array; }
    }
}
