// Generated by tools/ai/gen_clone.py. Do not edit by hand.
// Deep copy of a duel session for AI lookahead; no visuals are copied.
class CBetaGwentCloner extends IScriptable
{
    private var epoch, head : int;
    private var flipSeats : bool;
    private var originals, copies : array<IScriptable>;
    public function CloneSession(source : CBetaGwentDuelSession, stamp : int, optional reverseSeats : bool) : CBetaGwentDuelSession
    {
        var result : CBetaGwentDuelSession;
        epoch = stamp; head = 0; flipSeats = reverseSeats; originals.Clear(); copies.Clear();
        result = (CBetaGwentDuelSession)Obj(source);
        while (head < originals.Size()) { CopyAny(originals[head], copies[head]); head += 1; }
        return result;
    }
    private function Seat(value : int) : int
    { if (!flipSeats) return value; if (value == 1) return 2; if (value == 2) return 1; return value; }
    private function Winner(value : int) : int
    { if (!flipSeats) return value; return (value & -4) | ((value & 1) * 2) | ((value & 2) / 2); }
    private function StructSBetaGwentCardSnapshot(src : SBetaGwentCardSnapshot) : SBetaGwentCardSnapshot
    {
        var dst : SBetaGwentCardSnapshot;
        dst = src;
        dst.instanceId = src.instanceId;
        dst.originTemplateId = src.originTemplateId;
        dst.runtimeTemplate = src.runtimeTemplate;
        dst.ownerId = Seat(src.ownerId);
        dst.controllerId = Seat(src.controllerId);
        dst.positionPlayerId = Seat(src.positionPlayerId);
        dst.locationMask = src.locationMask;
        dst.locationIndex = src.locationIndex;
        dst.runtimeTierMask = src.runtimeTierMask;
        dst.tokenMask = src.tokenMask;
        dst.timerValue = src.timerValue;
        dst.power = src.power;
        dst.canBePlayed = src.canBePlayed;
        dst.isInExecutionStack = src.isInExecutionStack;
        dst.isWaitingToDie = src.isWaitingToDie;
        return dst;
    }
    private function StructSBetaGwentChoiceCandidate(src : SBetaGwentChoiceCandidate) : SBetaGwentChoiceCandidate
    {
        var dst : SBetaGwentChoiceCandidate;
        dst = src;
        dst.originalInstanceId = src.originalInstanceId;
        dst.positionPlayerId = Seat(src.positionPlayerId);
        dst.templateId = src.templateId;
        dst.deckFactionId = src.deckFactionId;
        return dst;
    }
    private function StructSBetaGwentChoiceEntry(src : SBetaGwentChoiceEntry) : SBetaGwentChoiceEntry
    {
        var dst : SBetaGwentChoiceEntry;
        dst = src;
        dst.view = src.view;
        dst.originalInstanceId = src.originalInstanceId;
        dst.positionPlayerId = Seat(src.positionPlayerId);
        return dst;
    }
    private function StructSBetaGwentDevelopmentCard(src : SBetaGwentDevelopmentCard) : SBetaGwentDevelopmentCard
    {
        var dst : SBetaGwentDevelopmentCard;
        dst = src;
        dst.card = StructSBetaGwentCardSnapshot(src.card);
        dst.title = src.title;
        dst.createdCopy = src.createdCopy;
        return dst;
    }
    private function StructSBetaGwentDuelCueContext(src : SBetaGwentDuelCueContext) : SBetaGwentDuelCueContext
    {
        var dst : SBetaGwentDuelCueContext;
        dst = src;
        dst.id = src.id;
        dst.templateId = src.templateId;
        dst.side = Seat(src.side);
        dst.row = src.row;
        return dst;
    }
    private function StructSBetaGwentMatchSnapshot(src : SBetaGwentMatchSnapshot) : SBetaGwentMatchSnapshot
    {
        var dst : SBetaGwentMatchSnapshot;
        dst = src;
        dst.initialized = src.initialized;
        dst.roundNumber = src.roundNumber;
        dst.turnSequence = src.turnSequence;
        dst.currentPlayerId = Seat(src.currentPlayerId);
        dst.startingPlayerId = Seat(src.startingPlayerId);
        dst.roundActive = src.roundActive;
        dst.turnActive = src.turnActive;
        if (flipSeats) { dst.playerOne = StructSBetaGwentPlayerState(src.playerTwo); } else { dst.playerOne = StructSBetaGwentPlayerState(src.playerOne); }
        if (flipSeats) { dst.playerTwo = StructSBetaGwentPlayerState(src.playerOne); } else { dst.playerTwo = StructSBetaGwentPlayerState(src.playerTwo); }
        dst.matchWinnerMask = Winner(src.matchWinnerMask);
        return dst;
    }
    private function StructSBetaGwentPendingRequestSlot(src : SBetaGwentPendingRequestSlot) : SBetaGwentPendingRequestSlot
    {
        var dst : SBetaGwentPendingRequestSlot;
        dst = src;
        dst.request = (CBetaGwentCardRequest)Obj(src.request);
        dst.continuation = (CBetaGwentAbilityContinuation)Obj(src.continuation);
        return dst;
    }
    private function StructSBetaGwentPlayRequest(src : SBetaGwentPlayRequest) : SBetaGwentPlayRequest
    {
        var dst : SBetaGwentPlayRequest;
        dst = src;
        dst.playerId = Seat(src.playerId);
        dst.requestedInstanceId = src.requestedInstanceId;
        return dst;
    }
    private function StructSBetaGwentPlayerState(src : SBetaGwentPlayerState) : SBetaGwentPlayerState
    {
        var dst : SBetaGwentPlayerState;
        dst = src;
        dst.playerId = Seat(src.playerId);
        dst.crowns = src.crowns;
        dst.hasPassed = src.hasPassed;
        dst.hasMadeInitialMoveForCurrentTurn = src.hasMadeInitialMoveForCurrentTurn;
        return dst;
    }
    private function StructSBetaGwentRequestSnapshot(src : SBetaGwentRequestSnapshot) : SBetaGwentRequestSnapshot
    {
        var dst : SBetaGwentRequestSnapshot;
        dst = src;
        dst.initialized = src.initialized;
        dst.requestId = src.requestId;
        dst.playerId = Seat(src.playerId);
        dst.targetPlayerId = Seat(src.targetPlayerId);
        dst.kind = src.kind;
        dst.limits = src.limits;
        dst.selectedCount = src.selectedCount;
        dst.validCount = src.validCount;
        dst.applied = src.applied;
        dst.destroyed = src.destroyed;
        dst.autoDestroy = src.autoDestroy;
        return dst;
    }
    private function StructSBetaGwentRoundResult(src : SBetaGwentRoundResult) : SBetaGwentRoundResult
    {
        var dst : SBetaGwentRoundResult;
        dst = src;
        dst.roundNumber = src.roundNumber;
        dst.startingPlayerId = Seat(src.startingPlayerId);
        if (flipSeats) { dst.scoreOne = src.scoreTwo; } else { dst.scoreOne = src.scoreOne; }
        if (flipSeats) { dst.scoreTwo = src.scoreOne; } else { dst.scoreTwo = src.scoreTwo; }
        dst.winnerMask = Winner(src.winnerMask);
        if (flipSeats) { dst.crownDeltaOne = src.crownDeltaTwo; } else { dst.crownDeltaOne = src.crownDeltaOne; }
        if (flipSeats) { dst.crownDeltaTwo = src.crownDeltaOne; } else { dst.crownDeltaTwo = src.crownDeltaTwo; }
        return dst;
    }
    private function StructSBetaGwentTriggerTicket(src : SBetaGwentTriggerTicket) : SBetaGwentTriggerTicket
    {
        var dst : SBetaGwentTriggerTicket;
        dst = src;
        dst.instanceId = src.instanceId;
        dst.ownerPresent = src.ownerPresent;
        dst.priority = src.priority;
        dst.locationMask = src.locationMask;
        dst.ownerPlayerId = Seat(src.ownerPlayerId);
        dst.ownerIndex = src.ownerIndex;
        return dst;
    }
    public function Obj(o : IScriptable) : IScriptable
    {
        var n : IScriptable;
        var r0 : CBetaGwentActionContext;
        var r1 : CBetaGwentActionServices;
        var r2 : CBetaGwentActionDriver;
        var r3 : CBetaGwentQueuedAction;
        var r4 : CBetaGwentActionSink;
        var r5 : CBetaGwentActionQueue;
        var r6 : CBetaGwentMatchState;
        var r7 : CBetaGwentPowerNumbers;
        var r8 : CBetaGwentRandomGenerator;
        var r9 : CBetaGwentRegistryCardReference;
        var r10 : CBetaGwentRegistryIdStore;
        var r11 : CBetaGwentAbilityContinuation;
        var r12 : CBetaGwentRequestStore;
        var r13 : CBetaGwentCardRequest;
        var r14 : CBetaGwentPublicResponseAI;
        var r15 : CBetaGwentAIChasePlanner;
        var r16 : CBetaGwentArchetypeAI;
        var r17 : CBetaGwentDuelPassiveFrame;
        var r18 : CBetaGwentDuelEvent;
        var r19 : CBetaGwentDuelEvents;
        var r20 : CBetaGwentDuelMonsters;
        var r21 : CBetaGwentDuelNeutral;
        var r22 : CBetaGwentNilfReaction;
        var r23 : CBetaGwentDuelNilf;
        var r24 : CBetaGwentNilfDependencies;
        var r25 : CBetaGwentDuelNorth;
        var r26 : CBetaGwentDuelScoia;
        var r27 : CBetaGwentDuelSession;
        var r28 : CBetaGwentDuelSkellige;
        var r29 : CBetaGwentDuelSpecials;
        var r30 : CBetaGwentDuelVisualFrame;
        var r31 : CBetaGwentDuelWeather;
        var r32 : CBetaGwentWeatherAI;
        var r33 : CBetaGwentDevelopmentRequestFlow;
        if (!o) return NULL;
        r0 = (CBetaGwentActionContext)o;
        if (r0) { if (r0.bgCloneEpoch == epoch) return r0.bgCloneRef; n = Make(o); r0.bgCloneEpoch = epoch; r0.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r1 = (CBetaGwentActionServices)o;
        if (r1) { if (r1.bgCloneEpoch == epoch) return r1.bgCloneRef; n = Make(o); r1.bgCloneEpoch = epoch; r1.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r2 = (CBetaGwentActionDriver)o;
        if (r2) { if (r2.bgCloneEpoch == epoch) return r2.bgCloneRef; n = Make(o); r2.bgCloneEpoch = epoch; r2.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r3 = (CBetaGwentQueuedAction)o;
        if (r3) { if (r3.bgCloneEpoch == epoch) return r3.bgCloneRef; n = Make(o); r3.bgCloneEpoch = epoch; r3.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r4 = (CBetaGwentActionSink)o;
        if (r4) { if (r4.bgCloneEpoch == epoch) return r4.bgCloneRef; n = Make(o); r4.bgCloneEpoch = epoch; r4.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r5 = (CBetaGwentActionQueue)o;
        if (r5) { if (r5.bgCloneEpoch == epoch) return r5.bgCloneRef; n = Make(o); r5.bgCloneEpoch = epoch; r5.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r6 = (CBetaGwentMatchState)o;
        if (r6) { if (r6.bgCloneEpoch == epoch) return r6.bgCloneRef; n = Make(o); r6.bgCloneEpoch = epoch; r6.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r7 = (CBetaGwentPowerNumbers)o;
        if (r7) { if (r7.bgCloneEpoch == epoch) return r7.bgCloneRef; n = Make(o); r7.bgCloneEpoch = epoch; r7.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r8 = (CBetaGwentRandomGenerator)o;
        if (r8) { if (r8.bgCloneEpoch == epoch) return r8.bgCloneRef; n = Make(o); r8.bgCloneEpoch = epoch; r8.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r9 = (CBetaGwentRegistryCardReference)o;
        if (r9) { if (r9.bgCloneEpoch == epoch) return r9.bgCloneRef; n = Make(o); r9.bgCloneEpoch = epoch; r9.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r10 = (CBetaGwentRegistryIdStore)o;
        if (r10) { if (r10.bgCloneEpoch == epoch) return r10.bgCloneRef; n = Make(o); r10.bgCloneEpoch = epoch; r10.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r11 = (CBetaGwentAbilityContinuation)o;
        if (r11) { if (r11.bgCloneEpoch == epoch) return r11.bgCloneRef; n = Make(o); r11.bgCloneEpoch = epoch; r11.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r12 = (CBetaGwentRequestStore)o;
        if (r12) { if (r12.bgCloneEpoch == epoch) return r12.bgCloneRef; n = Make(o); r12.bgCloneEpoch = epoch; r12.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r13 = (CBetaGwentCardRequest)o;
        if (r13) { if (r13.bgCloneEpoch == epoch) return r13.bgCloneRef; n = Make(o); r13.bgCloneEpoch = epoch; r13.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r14 = (CBetaGwentPublicResponseAI)o;
        if (r14) { if (r14.bgCloneEpoch == epoch) return r14.bgCloneRef; n = Make(o); r14.bgCloneEpoch = epoch; r14.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r15 = (CBetaGwentAIChasePlanner)o;
        if (r15) { if (r15.bgCloneEpoch == epoch) return r15.bgCloneRef; n = Make(o); r15.bgCloneEpoch = epoch; r15.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r16 = (CBetaGwentArchetypeAI)o;
        if (r16) { if (r16.bgCloneEpoch == epoch) return r16.bgCloneRef; n = Make(o); r16.bgCloneEpoch = epoch; r16.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r17 = (CBetaGwentDuelPassiveFrame)o;
        if (r17) { if (r17.bgCloneEpoch == epoch) return r17.bgCloneRef; n = Make(o); r17.bgCloneEpoch = epoch; r17.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r18 = (CBetaGwentDuelEvent)o;
        if (r18) { if (r18.bgCloneEpoch == epoch) return r18.bgCloneRef; n = Make(o); r18.bgCloneEpoch = epoch; r18.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r19 = (CBetaGwentDuelEvents)o;
        if (r19) { if (r19.bgCloneEpoch == epoch) return r19.bgCloneRef; n = Make(o); r19.bgCloneEpoch = epoch; r19.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r20 = (CBetaGwentDuelMonsters)o;
        if (r20) { if (r20.bgCloneEpoch == epoch) return r20.bgCloneRef; n = Make(o); r20.bgCloneEpoch = epoch; r20.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r21 = (CBetaGwentDuelNeutral)o;
        if (r21) { if (r21.bgCloneEpoch == epoch) return r21.bgCloneRef; n = Make(o); r21.bgCloneEpoch = epoch; r21.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r22 = (CBetaGwentNilfReaction)o;
        if (r22) { if (r22.bgCloneEpoch == epoch) return r22.bgCloneRef; n = Make(o); r22.bgCloneEpoch = epoch; r22.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r23 = (CBetaGwentDuelNilf)o;
        if (r23) { if (r23.bgCloneEpoch == epoch) return r23.bgCloneRef; n = Make(o); r23.bgCloneEpoch = epoch; r23.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r24 = (CBetaGwentNilfDependencies)o;
        if (r24) { if (r24.bgCloneEpoch == epoch) return r24.bgCloneRef; n = Make(o); r24.bgCloneEpoch = epoch; r24.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r25 = (CBetaGwentDuelNorth)o;
        if (r25) { if (r25.bgCloneEpoch == epoch) return r25.bgCloneRef; n = Make(o); r25.bgCloneEpoch = epoch; r25.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r26 = (CBetaGwentDuelScoia)o;
        if (r26) { if (r26.bgCloneEpoch == epoch) return r26.bgCloneRef; n = Make(o); r26.bgCloneEpoch = epoch; r26.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r27 = (CBetaGwentDuelSession)o;
        if (r27) { if (r27.bgCloneEpoch == epoch) return r27.bgCloneRef; n = Make(o); r27.bgCloneEpoch = epoch; r27.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r28 = (CBetaGwentDuelSkellige)o;
        if (r28) { if (r28.bgCloneEpoch == epoch) return r28.bgCloneRef; n = Make(o); r28.bgCloneEpoch = epoch; r28.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r29 = (CBetaGwentDuelSpecials)o;
        if (r29) { if (r29.bgCloneEpoch == epoch) return r29.bgCloneRef; n = Make(o); r29.bgCloneEpoch = epoch; r29.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r30 = (CBetaGwentDuelVisualFrame)o;
        if (r30) { if (r30.bgCloneEpoch == epoch) return r30.bgCloneRef; n = Make(o); r30.bgCloneEpoch = epoch; r30.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r31 = (CBetaGwentDuelWeather)o;
        if (r31) { if (r31.bgCloneEpoch == epoch) return r31.bgCloneRef; n = Make(o); r31.bgCloneEpoch = epoch; r31.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r32 = (CBetaGwentWeatherAI)o;
        if (r32) { if (r32.bgCloneEpoch == epoch) return r32.bgCloneRef; n = Make(o); r32.bgCloneEpoch = epoch; r32.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r33 = (CBetaGwentDevelopmentRequestFlow)o;
        if (r33) { if (r33.bgCloneEpoch == epoch) return r33.bgCloneRef; n = Make(o); r33.bgCloneEpoch = epoch; r33.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        return NULL;
    }
    private function Make(o : IScriptable) : IScriptable
    {
        if ((CBetaGwentDuelCreatedCardAction)o) return new CBetaGwentDuelCreatedCardAction in this;
        if ((CBetaGwentDuelEffectAction)o) return new CBetaGwentDuelEffectAction in this;
        if ((CBetaGwentDuelMoveAction)o) return new CBetaGwentDuelMoveAction in this;
        if ((CBetaGwentDuelRelocateAction)o) return new CBetaGwentDuelRelocateAction in this;
        if ((CBetaGwentDuelSpawnAction)o) return new CBetaGwentDuelSpawnAction in this;
        if ((CBetaGwentDuelTimerAction)o) return new CBetaGwentDuelTimerAction in this;
        if ((CBetaGwentMonsterDuelAction)o) return new CBetaGwentMonsterDuelAction in this;
        if ((CBetaGwentActionManager)o) return new CBetaGwentActionManager in this;
        if ((CBetaGwentDuelActionServices)o) return new CBetaGwentDuelActionServices in this;
        if ((CBetaGwentDuelCard)o) return new CBetaGwentDuelCard in this;
        if ((CBetaGwentDuelEffectRuntime)o) return new CBetaGwentDuelEffectRuntime in this;
        if ((CBetaGwentDuelPower)o) return new CBetaGwentDuelPower in this;
        if ((CBetaGwentDuelRegistry)o) return new CBetaGwentDuelRegistry in this;
        if ((CBetaGwentManagerContext)o) return new CBetaGwentManagerContext in this;
        if ((CBetaGwentAIChasePlanner)o) return new CBetaGwentAIChasePlanner in this;
        if ((CBetaGwentAbilityContinuation)o) return new CBetaGwentAbilityContinuation in this;
        if ((CBetaGwentActionContext)o) return new CBetaGwentActionContext in this;
        if ((CBetaGwentActionDriver)o) return new CBetaGwentActionDriver in this;
        if ((CBetaGwentActionQueue)o) return new CBetaGwentActionQueue in this;
        if ((CBetaGwentArchetypeAI)o) return new CBetaGwentArchetypeAI in this;
        if ((CBetaGwentCardRequest)o) return new CBetaGwentCardRequest in this;
        if ((CBetaGwentDevelopmentRequestFlow)o) return new CBetaGwentDevelopmentRequestFlow in this;
        if ((CBetaGwentDuelEvent)o) return new CBetaGwentDuelEvent in this;
        if ((CBetaGwentDuelEvents)o) return new CBetaGwentDuelEvents in this;
        if ((CBetaGwentDuelMonsters)o) return new CBetaGwentDuelMonsters in this;
        if ((CBetaGwentDuelNeutral)o) return new CBetaGwentDuelNeutral in this;
        if ((CBetaGwentDuelNilf)o) return new CBetaGwentDuelNilf in this;
        if ((CBetaGwentDuelNorth)o) return new CBetaGwentDuelNorth in this;
        if ((CBetaGwentDuelPassiveFrame)o) return new CBetaGwentDuelPassiveFrame in this;
        if ((CBetaGwentDuelScoia)o) return new CBetaGwentDuelScoia in this;
        if ((CBetaGwentDuelSession)o) return new CBetaGwentDuelSession in this;
        if ((CBetaGwentDuelSkellige)o) return new CBetaGwentDuelSkellige in this;
        if ((CBetaGwentDuelSpecials)o) return new CBetaGwentDuelSpecials in this;
        if ((CBetaGwentDuelVisualFrame)o) return new CBetaGwentDuelVisualFrame in this;
        if ((CBetaGwentDuelWeather)o) return new CBetaGwentDuelWeather in this;
        if ((CBetaGwentMatchState)o) return new CBetaGwentMatchState in this;
        if ((CBetaGwentNilfDependencies)o) return new CBetaGwentNilfDependencies in this;
        if ((CBetaGwentNilfReaction)o) return new CBetaGwentNilfReaction in this;
        if ((CBetaGwentPublicResponseAI)o) return new CBetaGwentPublicResponseAI in this;
        if ((CBetaGwentQueuedAction)o) return new CBetaGwentQueuedAction in this;
        if ((CBetaGwentRandomGenerator)o) return new CBetaGwentRandomGenerator in this;
        if ((CBetaGwentRegistryCardReference)o) return new CBetaGwentRegistryCardReference in this;
        if ((CBetaGwentRegistryIdStore)o) return new CBetaGwentRegistryIdStore in this;
        if ((CBetaGwentRequestStore)o) return new CBetaGwentRequestStore in this;
        if ((CBetaGwentWeatherAI)o) return new CBetaGwentWeatherAI in this;
        return NULL;
    }
    private function CopyAny(src : IScriptable, dst : IScriptable)
    {
        if ((CBetaGwentDuelCreatedCardAction)src) { CopyDuelCreatedCardAction((CBetaGwentDuelCreatedCardAction)src, (CBetaGwentDuelCreatedCardAction)dst); return; }
        if ((CBetaGwentDuelEffectAction)src) { CopyDuelEffectAction((CBetaGwentDuelEffectAction)src, (CBetaGwentDuelEffectAction)dst); return; }
        if ((CBetaGwentDuelMoveAction)src) { CopyDuelMoveAction((CBetaGwentDuelMoveAction)src, (CBetaGwentDuelMoveAction)dst); return; }
        if ((CBetaGwentDuelRelocateAction)src) { CopyDuelRelocateAction((CBetaGwentDuelRelocateAction)src, (CBetaGwentDuelRelocateAction)dst); return; }
        if ((CBetaGwentDuelSpawnAction)src) { CopyDuelSpawnAction((CBetaGwentDuelSpawnAction)src, (CBetaGwentDuelSpawnAction)dst); return; }
        if ((CBetaGwentDuelTimerAction)src) { CopyDuelTimerAction((CBetaGwentDuelTimerAction)src, (CBetaGwentDuelTimerAction)dst); return; }
        if ((CBetaGwentMonsterDuelAction)src) { CopyMonsterDuelAction((CBetaGwentMonsterDuelAction)src, (CBetaGwentMonsterDuelAction)dst); return; }
        if ((CBetaGwentActionManager)src) { CopyActionManager((CBetaGwentActionManager)src, (CBetaGwentActionManager)dst); return; }
        if ((CBetaGwentDuelActionServices)src) { CopyDuelActionServices((CBetaGwentDuelActionServices)src, (CBetaGwentDuelActionServices)dst); return; }
        if ((CBetaGwentDuelCard)src) { CopyDuelCard((CBetaGwentDuelCard)src, (CBetaGwentDuelCard)dst); return; }
        if ((CBetaGwentDuelEffectRuntime)src) { CopyDuelEffectRuntime((CBetaGwentDuelEffectRuntime)src, (CBetaGwentDuelEffectRuntime)dst); return; }
        if ((CBetaGwentDuelPower)src) { CopyDuelPower((CBetaGwentDuelPower)src, (CBetaGwentDuelPower)dst); return; }
        if ((CBetaGwentDuelRegistry)src) { CopyDuelRegistry((CBetaGwentDuelRegistry)src, (CBetaGwentDuelRegistry)dst); return; }
        if ((CBetaGwentManagerContext)src) { CopyManagerContext((CBetaGwentManagerContext)src, (CBetaGwentManagerContext)dst); return; }
        if ((CBetaGwentAIChasePlanner)src) { CopyAIChasePlanner((CBetaGwentAIChasePlanner)src, (CBetaGwentAIChasePlanner)dst); return; }
        if ((CBetaGwentAbilityContinuation)src) { CopyAbilityContinuation((CBetaGwentAbilityContinuation)src, (CBetaGwentAbilityContinuation)dst); return; }
        if ((CBetaGwentActionContext)src) { CopyActionContext((CBetaGwentActionContext)src, (CBetaGwentActionContext)dst); return; }
        if ((CBetaGwentActionDriver)src) { CopyActionDriver((CBetaGwentActionDriver)src, (CBetaGwentActionDriver)dst); return; }
        if ((CBetaGwentActionQueue)src) { CopyActionQueue((CBetaGwentActionQueue)src, (CBetaGwentActionQueue)dst); return; }
        if ((CBetaGwentArchetypeAI)src) { CopyArchetypeAI((CBetaGwentArchetypeAI)src, (CBetaGwentArchetypeAI)dst); return; }
        if ((CBetaGwentCardRequest)src) { CopyCardRequest((CBetaGwentCardRequest)src, (CBetaGwentCardRequest)dst); return; }
        if ((CBetaGwentDevelopmentRequestFlow)src) { CopyDevelopmentRequestFlow((CBetaGwentDevelopmentRequestFlow)src, (CBetaGwentDevelopmentRequestFlow)dst); return; }
        if ((CBetaGwentDuelEvent)src) { CopyDuelEvent((CBetaGwentDuelEvent)src, (CBetaGwentDuelEvent)dst); return; }
        if ((CBetaGwentDuelEvents)src) { CopyDuelEvents((CBetaGwentDuelEvents)src, (CBetaGwentDuelEvents)dst); return; }
        if ((CBetaGwentDuelMonsters)src) { CopyDuelMonsters((CBetaGwentDuelMonsters)src, (CBetaGwentDuelMonsters)dst); return; }
        if ((CBetaGwentDuelNeutral)src) { CopyDuelNeutral((CBetaGwentDuelNeutral)src, (CBetaGwentDuelNeutral)dst); return; }
        if ((CBetaGwentDuelNilf)src) { CopyDuelNilf((CBetaGwentDuelNilf)src, (CBetaGwentDuelNilf)dst); return; }
        if ((CBetaGwentDuelNorth)src) { CopyDuelNorth((CBetaGwentDuelNorth)src, (CBetaGwentDuelNorth)dst); return; }
        if ((CBetaGwentDuelPassiveFrame)src) { CopyDuelPassiveFrame((CBetaGwentDuelPassiveFrame)src, (CBetaGwentDuelPassiveFrame)dst); return; }
        if ((CBetaGwentDuelScoia)src) { CopyDuelScoia((CBetaGwentDuelScoia)src, (CBetaGwentDuelScoia)dst); return; }
        if ((CBetaGwentDuelSession)src) { CopyDuelSession((CBetaGwentDuelSession)src, (CBetaGwentDuelSession)dst); return; }
        if ((CBetaGwentDuelSkellige)src) { CopyDuelSkellige((CBetaGwentDuelSkellige)src, (CBetaGwentDuelSkellige)dst); return; }
        if ((CBetaGwentDuelSpecials)src) { CopyDuelSpecials((CBetaGwentDuelSpecials)src, (CBetaGwentDuelSpecials)dst); return; }
        if ((CBetaGwentDuelVisualFrame)src) { CopyDuelVisualFrame((CBetaGwentDuelVisualFrame)src, (CBetaGwentDuelVisualFrame)dst); return; }
        if ((CBetaGwentDuelWeather)src) { CopyDuelWeather((CBetaGwentDuelWeather)src, (CBetaGwentDuelWeather)dst); return; }
        if ((CBetaGwentMatchState)src) { CopyMatchState((CBetaGwentMatchState)src, (CBetaGwentMatchState)dst); return; }
        if ((CBetaGwentNilfDependencies)src) { CopyNilfDependencies((CBetaGwentNilfDependencies)src, (CBetaGwentNilfDependencies)dst); return; }
        if ((CBetaGwentNilfReaction)src) { CopyNilfReaction((CBetaGwentNilfReaction)src, (CBetaGwentNilfReaction)dst); return; }
        if ((CBetaGwentPublicResponseAI)src) { CopyPublicResponseAI((CBetaGwentPublicResponseAI)src, (CBetaGwentPublicResponseAI)dst); return; }
        if ((CBetaGwentQueuedAction)src) { CopyQueuedAction((CBetaGwentQueuedAction)src, (CBetaGwentQueuedAction)dst); return; }
        if ((CBetaGwentRandomGenerator)src) { CopyRandomGenerator((CBetaGwentRandomGenerator)src, (CBetaGwentRandomGenerator)dst); return; }
        if ((CBetaGwentRegistryCardReference)src) { CopyRegistryCardReference((CBetaGwentRegistryCardReference)src, (CBetaGwentRegistryCardReference)dst); return; }
        if ((CBetaGwentRegistryIdStore)src) { CopyRegistryIdStore((CBetaGwentRegistryIdStore)src, (CBetaGwentRegistryIdStore)dst); return; }
        if ((CBetaGwentRequestStore)src) { CopyRequestStore((CBetaGwentRequestStore)src, (CBetaGwentRequestStore)dst); return; }
        if ((CBetaGwentWeatherAI)src) { CopyWeatherAI((CBetaGwentWeatherAI)src, (CBetaGwentWeatherAI)dst); return; }
    }
    private function CopyDuelCreatedCardAction(src : CBetaGwentDuelCreatedCardAction, dst : CBetaGwentDuelCreatedCardAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.templateId = src.templateId;
        dst.instanceId = src.instanceId;
    }
    private function CopyDuelEffectAction(src : CBetaGwentDuelEffectAction, dst : CBetaGwentDuelEffectAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.attacker = (CBetaGwentDuelCard)Obj(src.attacker);
        dst.target = (CBetaGwentDuelCard)Obj(src.target);
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.operation = src.operation;
        dst.amount = src.amount;
        dst.allowedLocations = src.allowedLocations;
        dst.ignoreArmor = src.ignoreArmor;
        dst.attackId = src.attackId;
    }
    private function CopyDuelMoveAction(src : CBetaGwentDuelMoveAction, dst : CBetaGwentDuelMoveAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.destination = StructSBetaGwentCardSnapshot(src.destination);
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
    }
    private function CopyDuelRelocateAction(src : CBetaGwentDuelRelocateAction, dst : CBetaGwentDuelRelocateAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
        dst.side = Seat(src.side);
        dst.row = src.row;
        dst.resetHand = src.resetHand;
    }
    private function CopyDuelSpawnAction(src : CBetaGwentDuelSpawnAction, dst : CBetaGwentDuelSpawnAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.fromPosition = StructSBetaGwentCardSnapshot(src.fromPosition);
        dst.templateId = src.templateId;
        dst.ids = src.ids;
    }
    private function CopyDuelTimerAction(src : CBetaGwentDuelTimerAction, dst : CBetaGwentDuelTimerAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
        dst.operation = src.operation;
        dst.value = src.value;
    }
    private function CopyMonsterDuelAction(src : CBetaGwentMonsterDuelAction, dst : CBetaGwentMonsterDuelAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.target = (CBetaGwentDuelCard)Obj(src.target);
        dst.retaliation = src.retaliation;
        dst.heal = src.heal;
        dst.armor = src.armor;
    }
    private function CopyActionManager(src : CBetaGwentActionManager, dst : CBetaGwentActionManager)
    {
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.services = (CBetaGwentActionServices)Obj(src.services);
        dst.initialized = src.initialized;
        dst.lastKnownNetworkId = src.lastKnownNetworkId;
        dst.fault = src.fault;
        dst.dispatches = src.dispatches;
    }
    private function CopyDuelActionServices(src : CBetaGwentDuelActionServices, dst : CBetaGwentDuelActionServices)
    {
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
    }
    private function CopyDuelCard(src : CBetaGwentDuelCard, dst : CBetaGwentDuelCard)
    {
        dst.cardState = StructSBetaGwentCardSnapshot(src.cardState);
        dst.definition = src.definition;
        dst.power = (CBetaGwentDuelPower)Obj(src.power);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.consumeAttackerId = src.consumeAttackerId;
        dst.playedChild = (CBetaGwentDuelCard)Obj(src.playedChild);
        dst.monsterStage = src.monsterStage;
        dst.monsterRemaining = src.monsterRemaining;
        dst.monsterStored = src.monsterStored;
        dst.monsterOnce = src.monsterOnce;
        dst.playFromLocation = src.playFromLocation;
        dst.lastActiveRow = src.lastActiveRow;
        dst.northernCrew = src.northernCrew;
        dst.nilfCounter = src.nilfCounter;
        dst.neutralChoice = src.neutralChoice;
        dst.createdCopy = src.createdCopy;
        dst.monsterIds = src.monsterIds;
        dst.selectedModeId = src.selectedModeId;
    }
    private function CopyDuelEffectRuntime(src : CBetaGwentDuelEffectRuntime, dst : CBetaGwentDuelEffectRuntime)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.queue = (CBetaGwentActionQueue)Obj(src.queue);
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.manager = (CBetaGwentActionManager)Obj(src.manager);
        dst.services = (CBetaGwentDuelActionServices)Obj(src.services);
        dst.frames = src.frames;
        for (i = 0; i < dst.frames.Size(); i += 1) dst.frames[i] = (CBetaGwentDuelPassiveFrame)Obj(dst.frames[i]);
        dst.buildingFrame = (CBetaGwentDuelPassiveFrame)Obj(src.buildingFrame);
        dst.dispatchingFrame = (CBetaGwentDuelPassiveFrame)Obj(src.dispatchingFrame);
        dst.passiveCount = src.passiveCount;
        dst.maximumDepth = src.maximumDepth;
        dst.failed = src.failed;
        dst.running = src.running;
        dst.beforeCount = src.beforeCount;
        dst.appliedCount = src.appliedCount;
        dst.afterCount = src.afterCount;
        dst.skippedCount = src.skippedCount;
        dst.attackSerial = src.attackSerial;
        dst.attackKey = src.attackKey;
        dst.attackSource = (CBetaGwentDuelCard)Obj(src.attackSource);
        dst.attackOpen = src.attackOpen;
    }
    private function CopyDuelPower(src : CBetaGwentDuelPower, dst : CBetaGwentDuelPower)
    {
        dst.initialized = src.initialized;
        dst.basePower = src.basePower;
        dst.permanentPower = src.permanentPower;
        dst.currentPower = src.currentPower;
        dst.currentArmor = src.currentArmor;
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
    }
    private function CopyDuelRegistry(src : CBetaGwentDuelRegistry, dst : CBetaGwentDuelRegistry)
    {
        var i : int;
        dst.initialized = src.initialized;
        dst.nextId = src.nextId;
        dst.recycled = src.recycled;
        dst.cards = src.cards;
        for (i = 0; i < dst.cards.Size(); i += 1) dst.cards[i] = (CBetaGwentRegistryCardReference)Obj(dst.cards[i]);
    }
    private function CopyManagerContext(src : CBetaGwentManagerContext, dst : CBetaGwentManagerContext)
    {
        dst.authority = src.authority;
        dst.mainController = src.mainController;
        dst.verbose = src.verbose;
        dst.dirty = src.dirty;
    }
    private function CopyAIChasePlanner(src : CBetaGwentAIChasePlanner, dst : CBetaGwentAIChasePlanner)
    {
    }
    private function CopyAbilityContinuation(src : CBetaGwentAbilityContinuation, dst : CBetaGwentAbilityContinuation)
    {
        dst.ownerInstanceId = src.ownerInstanceId;
        dst.nodeId = src.nodeId;
        dst.nodeSetup = src.nodeSetup;
        dst.completedNodes = src.completedNodes;
        dst.phase = src.phase;
        dst.pending = (CBetaGwentCardRequest)Obj(src.pending);
    }
    private function CopyActionContext(src : CBetaGwentActionContext, dst : CBetaGwentActionContext)
    {
        dst.authority = src.authority;
    }
    private function CopyActionDriver(src : CBetaGwentActionDriver, dst : CBetaGwentActionDriver)
    {
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.manager = (CBetaGwentActionManager)Obj(src.manager);
        dst.queue = (CBetaGwentActionQueue)Obj(src.queue);
    }
    private function CopyActionQueue(src : CBetaGwentActionQueue, dst : CBetaGwentActionQueue)
    {
        var i : int;
        dst.actions = src.actions;
        for (i = 0; i < dst.actions.Size(); i += 1) dst.actions[i] = (CBetaGwentQueuedAction)Obj(dst.actions[i]);
        dst.sink = (CBetaGwentActionSink)Obj(src.sink);
        dst.initialized = src.initialized;
        dst.authority = src.authority;
        dst.authorityContext = (CBetaGwentActionContext)Obj(src.authorityContext);
        dst.abilityLocal = src.abilityLocal;
    }
    private function CopyArchetypeAI(src : CBetaGwentArchetypeAI, dst : CBetaGwentArchetypeAI)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.profile = src.profile;
        dst.family = src.family;
        dst.pairs = src.pairs;
        dst.hand = src.hand;
        for (i = 0; i < dst.hand.Size(); i += 1) dst.hand[i] = (CBetaGwentDuelCard)Obj(dst.hand[i]);
        dst.board = src.board;
        for (i = 0; i < dst.board.Size(); i += 1) dst.board[i] = (CBetaGwentDuelCard)Obj(dst.board[i]);
        dst.situation = StructSBetaGwentMatchSnapshot(src.situation);
    }
    private function CopyCardRequest(src : CBetaGwentCardRequest, dst : CBetaGwentCardRequest)
    {
        var i : int;
        dst.requestState = StructSBetaGwentRequestSnapshot(src.requestState);
        dst.choices = src.choices;
        for (i = 0; i < dst.choices.Size(); i += 1) dst.choices[i] = StructSBetaGwentChoiceEntry(dst.choices[i]);
        dst.validTargets = src.validTargets;
        dst.selected = src.selected;
        dst.targetsInShape = src.targetsInShape;
    }
    private function CopyDevelopmentRequestFlow(src : CBetaGwentDevelopmentRequestFlow, dst : CBetaGwentDevelopmentRequestFlow)
    {
        var i : int;
        dst.pending = (CBetaGwentCardRequest)Obj(src.pending);
        dst.continuation = (CBetaGwentAbilityContinuation)Obj(src.continuation);
        dst.store = (CBetaGwentRequestStore)Obj(src.store);
        dst.nextRequestId = src.nextRequestId;
        dst.completed = src.completed;
        dst.aborted = src.aborted;
        dst.sourceCards = src.sourceCards;
        for (i = 0; i < dst.sourceCards.Size(); i += 1) dst.sourceCards[i] = StructSBetaGwentDevelopmentCard(dst.sourceCards[i]);
        dst.lastResult = src.lastResult;
        dst.message = src.message;
        dst.isolatedCheck = src.isolatedCheck;
    }
    private function CopyDuelEvent(src : CBetaGwentDuelEvent, dst : CBetaGwentDuelEvent)
    {
        dst.kind = src.kind;
        dst.batchSerial = src.batchSerial;
        dst.source = StructSBetaGwentCardSnapshot(src.source);
        dst.cause = StructSBetaGwentCardSnapshot(src.cause);
        dst.rowToken = src.rowToken;
        dst.rowTargets = src.rowTargets;
        dst.banishedConsume = src.banishedConsume;
    }
    private function CopyDuelEvents(src : CBetaGwentDuelEvents, dst : CBetaGwentDuelEvents)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.pending = src.pending;
        for (i = 0; i < dst.pending.Size(); i += 1) dst.pending[i] = (CBetaGwentDuelEvent)Obj(dst.pending[i]);
        dst.batchSerial = src.batchSerial;
    }
    private function CopyDuelMonsters(src : CBetaGwentDuelMonsters, dst : CBetaGwentDuelMonsters)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.north = (CBetaGwentDuelNorth)Obj(src.north);
        dst.nilf = (CBetaGwentDuelNilf)Obj(src.nilf);
        dst.neutral = (CBetaGwentDuelNeutral)Obj(src.neutral);
        dst.skellige = (CBetaGwentDuelSkellige)Obj(src.skellige);
        dst.scoia = (CBetaGwentDuelScoia)Obj(src.scoia);
    }
    private function CopyDuelNeutral(src : CBetaGwentDuelNeutral, dst : CBetaGwentDuelNeutral)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
    private function CopyDuelNilf(src : CBetaGwentDuelNilf, dst : CBetaGwentDuelNilf)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.dependencies = (CBetaGwentNilfDependencies)Obj(src.dependencies);
    }
    private function CopyDuelNorth(src : CBetaGwentDuelNorth, dst : CBetaGwentDuelNorth)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
    private function CopyDuelPassiveFrame(src : CBetaGwentDuelPassiveFrame, dst : CBetaGwentDuelPassiveFrame)
    {
        dst.actions = (CBetaGwentActionQueue)Obj(src.actions);
        dst.source = StructSBetaGwentCardSnapshot(src.source);
        dst.batchSerial = src.batchSerial;
    }
    private function CopyDuelScoia(src : CBetaGwentDuelScoia, dst : CBetaGwentDuelScoia)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        if (flipSeats) dst.historyOne = src.historyTwo; else dst.historyOne = src.historyOne;
        if (flipSeats) dst.historyTwo = src.historyOne; else dst.historyTwo = src.historyTwo;
    }
    private function CopyDuelSession(src : CBetaGwentDuelSession, dst : CBetaGwentDuelSession)
    {
        var i : int;
        dst.events = (CBetaGwentDuelEvents)Obj(src.events);
        dst.drainingDeaths = src.drainingDeaths;
        dst.effects = (CBetaGwentDuelEffectRuntime)Obj(src.effects);
        dst.playStack = src.playStack;
        for (i = 0; i < dst.playStack.Size(); i += 1) dst.playStack[i] = (CBetaGwentDuelCard)Obj(dst.playStack[i]);
        dst.match = (CBetaGwentMatchState)Obj(src.match);
        dst.registry = (CBetaGwentDuelRegistry)Obj(src.registry);
        dst.live = src.live;
        for (i = 0; i < dst.live.Size(); i += 1) dst.live[i] = (CBetaGwentDuelCard)Obj(dst.live[i]);
        dst.dying = src.dying;
        for (i = 0; i < dst.dying.Size(); i += 1) dst.dying[i] = (CBetaGwentDuelCard)Obj(dst.dying[i]);
        dst.pendingConsumeVisuals = src.pendingConsumeVisuals;
        dst.message = src.message;
        dst.waiting = src.waiting;
        dst.fatal = src.fatal;
        dst.pendingCard = (CBetaGwentDuelCard)Obj(src.pendingCard);
        dst.pendingLeader = (CBetaGwentDuelCard)Obj(src.pendingLeader);
        dst.pendingRally = (CBetaGwentDuelCard)Obj(src.pendingRally);
        dst.pendingChoice = src.pendingChoice;
        dst.weather = (CBetaGwentDuelWeather)Obj(src.weather);
        dst.specials = (CBetaGwentDuelSpecials)Obj(src.specials);
        dst.monsters = (CBetaGwentDuelMonsters)Obj(src.monsters);
        dst.monsterMinimum = src.monsterMinimum;
        dst.monsterMaximum = src.monsterMaximum;
        dst.specialHitsLeft = src.specialHitsLeft;
        dst.handPowerTarget = src.handPowerTarget;
        dst.pendingHandPower = src.pendingHandPower;
        dst.pendingPileChoice = src.pendingPileChoice;
        dst.pendingIds = src.pendingIds;
        dst.requestId = src.requestId;
        dst.pendingRow = src.pendingRow;
        dst.random = (CBetaGwentRandomGenerator)Obj(src.random);
        dst.mulligan = src.mulligan;
        dst.mulliganBudget = src.mulliganBudget;
        dst.mulliganUsed = src.mulliganUsed;
        dst.roundStarter = Seat(src.roundStarter);
        dst.blacklistedTemplates = src.blacklistedTemplates;
        dst.reservedCards = src.reservedCards;
        dst.visualFrames.Clear();
        dst.recordVisuals = src.recordVisuals;
        dst.visualOverflow = src.visualOverflow;
        dst.visualSourceId = src.visualSourceId;
        dst.visualTemplateId = src.visualTemplateId;
        dst.visualSide = Seat(src.visualSide);
        dst.visualRow = src.visualRow;
        dst.visualAttack = src.visualAttack;
        dst.visualAttackTargets = src.visualAttackTargets;
        if (flipSeats) { dst.presetOne = src.presetTwo; } else { dst.presetOne = src.presetOne; }
        if (flipSeats) { dst.presetTwo = src.presetOne; } else { dst.presetTwo = src.presetTwo; }
        if (flipSeats) { dst.leaderTemplateOne = src.leaderTemplateTwo; } else { dst.leaderTemplateOne = src.leaderTemplateOne; }
        if (flipSeats) { dst.leaderTemplateTwo = src.leaderTemplateOne; } else { dst.leaderTemplateTwo = src.leaderTemplateTwo; }
        dst.nilfJobs = src.nilfJobs;
        for (i = 0; i < dst.nilfJobs.Size(); i += 1) dst.nilfJobs[i] = (CBetaGwentNilfReaction)Obj(dst.nilfJobs[i]);
        dst.nilfJob = (CBetaGwentNilfReaction)Obj(src.nilfJob);
        dst.nilfEndingTurn = src.nilfEndingTurn;
        dst.mulliganReactions = src.mulliganReactions;
        if (flipSeats) dst.nilfInitialOne = src.nilfInitialTwo; else dst.nilfInitialOne = src.nilfInitialOne;
        if (flipSeats) dst.nilfInitialTwo = src.nilfInitialOne; else dst.nilfInitialTwo = src.nilfInitialTwo;
        if (flipSeats) { dst.nilfSpellOne = src.nilfSpellTwo; } else { dst.nilfSpellOne = src.nilfSpellOne; }
        if (flipSeats) { dst.nilfSpellTwo = src.nilfSpellOne; } else { dst.nilfSpellTwo = src.nilfSpellTwo; }
        dst.nilfLastMovedUnit = src.nilfLastMovedUnit;
        dst.weatherAI = (CBetaGwentWeatherAI)Obj(src.weatherAI);
        dst.weatherProfile = src.weatherProfile;
        dst.archetypeAI = (CBetaGwentArchetypeAI)Obj(src.archetypeAI);
        dst.aiChaseRound = src.aiChaseRound;
        dst.aiChaseInitialHand = src.aiChaseInitialHand;
        dst.aiChaseSpent = src.aiChaseSpent;
        dst.aiObservedRound = src.aiObservedRound;
        dst.aiObservedEnemyScore = src.aiObservedEnemyScore;
        dst.aiPublicTempo = src.aiPublicTempo;
        if (flipSeats) { dst.aiRoundHandOne = src.aiRoundHandTwo; } else { dst.aiRoundHandOne = src.aiRoundHandOne; }
        if (flipSeats) { dst.aiRoundHandTwo = src.aiRoundHandOne; } else { dst.aiRoundHandTwo = src.aiRoundHandTwo; }
        dst.aiPlacing = src.aiPlacing;
        dst.aiSimulating = src.aiSimulating;
        dst.aiCloneEpoch = src.aiCloneEpoch;
        dst.aiSimCloner = src.aiSimCloner;
        dst.aiSimDamp = src.aiSimDamp;
        dst.aiDecisionSerial = src.aiDecisionSerial;
        dst.effectSourceDepth = src.effectSourceDepth;
        dst.savedSourceId = src.savedSourceId;
        dst.savedSourceTemplate = src.savedSourceTemplate;
        dst.savedSourceSide = Seat(src.savedSourceSide);
        dst.savedSourceRow = src.savedSourceRow;
        dst.aiLastStrategicValue = src.aiLastStrategicValue;
    }
    private function CopyDuelSkellige(src : CBetaGwentDuelSkellige, dst : CBetaGwentDuelSkellige)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        if (flipSeats) { dst.beastsOne = src.beastsTwo; } else { dst.beastsOne = src.beastsOne; }
        if (flipSeats) { dst.beastsTwo = src.beastsOne; } else { dst.beastsTwo = src.beastsTwo; }
    }
    private function CopyDuelSpecials(src : CBetaGwentDuelSpecials, dst : CBetaGwentDuelSpecials)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.weather = (CBetaGwentDuelWeather)Obj(src.weather);
    }
    private function CopyDuelVisualFrame(src : CBetaGwentDuelVisualFrame, dst : CBetaGwentDuelVisualFrame)
    {
        var i : int;
        dst.matchState = StructSBetaGwentMatchSnapshot(src.matchState);
        dst.cards = src.cards;
        for (i = 0; i < dst.cards.Size(); i += 1) dst.cards[i] = StructSBetaGwentDevelopmentCard(dst.cards[i]);
        dst.weatherTokens = src.weatherTokens;
        dst.weatherDamage = src.weatherDamage;
        if (flipSeats) { dst.scoreOne = src.scoreTwo; } else { dst.scoreOne = src.scoreOne; }
        if (flipSeats) { dst.scoreTwo = src.scoreOne; } else { dst.scoreTwo = src.scoreTwo; }
        dst.flags = src.flags;
        dst.enemyHand = src.enemyHand;
        if (flipSeats) { dst.graveOne = src.graveTwo; } else { dst.graveOne = src.graveOne; }
        if (flipSeats) { dst.graveTwo = src.graveOne; } else { dst.graveTwo = src.graveTwo; }
        if (flipSeats) { dst.deckOne = src.deckTwo; } else { dst.deckOne = src.deckOne; }
        if (flipSeats) { dst.deckTwo = src.deckOne; } else { dst.deckTwo = src.deckTwo; }
        if (flipSeats) { dst.leaderOne = src.leaderTwo; } else { dst.leaderOne = src.leaderOne; }
        if (flipSeats) { dst.leaderTwo = src.leaderOne; } else { dst.leaderTwo = src.leaderTwo; }
        dst.status = src.status;
        dst.kind = src.kind;
        dst.sourceId = src.sourceId;
        dst.targetId = src.targetId;
        dst.side = Seat(src.side);
        dst.row = src.row;
        dst.templateId = src.templateId;
        dst.duration = src.duration;
        dst.targetTemplateId = src.targetTemplateId;
        dst.targetPower = src.targetPower;
        dst.targetSide = Seat(src.targetSide);
        dst.targetZone = src.targetZone;
        dst.audioKind = src.audioKind;
        dst.attackId = src.attackId;
        dst.attackCount = src.attackCount;
    }
    private function CopyDuelWeather(src : CBetaGwentDuelWeather, dst : CBetaGwentDuelWeather)
    {
        var i : int;
        var swap : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.hazards = src.hazards;
        dst.dreamRows = src.dreamRows;
        if (flipSeats) {
            for (i = 0; i < 3 && i + 3 < dst.hazards.Size(); i += 1) { swap = dst.hazards[i]; dst.hazards[i] = dst.hazards[i+3]; dst.hazards[i+3] = swap; }
            for (i = 0; i < dst.dreamRows.Size(); i += 1) dst.dreamRows[i] = (dst.dreamRows[i]+3)%6;
        }
    }
    private function CopyMatchState(src : CBetaGwentMatchState, dst : CBetaGwentMatchState)
    {
        var i : int;
        dst.initialized = src.initialized;
        if (flipSeats) { dst.playerOne = StructSBetaGwentPlayerState(src.playerTwo); } else { dst.playerOne = StructSBetaGwentPlayerState(src.playerOne); }
        if (flipSeats) { dst.playerTwo = StructSBetaGwentPlayerState(src.playerOne); } else { dst.playerTwo = StructSBetaGwentPlayerState(src.playerTwo); }
        dst.roundNumber = src.roundNumber;
        dst.turnSequence = src.turnSequence;
        dst.startingPlayerId = Seat(src.startingPlayerId);
        dst.currentPlayerId = Seat(src.currentPlayerId);
        dst.roundActive = src.roundActive;
        dst.turnActive = src.turnActive;
        dst.results = src.results;
        for (i = 0; i < dst.results.Size(); i += 1) dst.results[i] = StructSBetaGwentRoundResult(dst.results[i]);
    }
    private function CopyNilfDependencies(src : CBetaGwentNilfDependencies, dst : CBetaGwentNilfDependencies)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.nilf = (CBetaGwentDuelNilf)Obj(src.nilf);
    }
    private function CopyNilfReaction(src : CBetaGwentNilfReaction, dst : CBetaGwentNilfReaction)
    {
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.kind = src.kind;
        dst.side = Seat(src.side);
    }
    private function CopyPublicResponseAI(src : CBetaGwentPublicResponseAI, dst : CBetaGwentPublicResponseAI)
    {
        dst.templates = src.templates;
        dst.weights = src.weights;
        dst.evaluated = src.evaluated;
        dst.rejected = src.rejected;
        dst.eligibleProfiles = src.eligibleProfiles;
        dst.penalty = src.penalty;
    }
    private function CopyQueuedAction(src : CBetaGwentQueuedAction, dst : CBetaGwentQueuedAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
    }
    private function CopyRandomGenerator(src : CBetaGwentRandomGenerator, dst : CBetaGwentRandomGenerator)
    {
        dst.words = src.words;
        dst.remaining = src.remaining;
        dst.cursor = src.cursor;
        dst.reseedValue = src.reseedValue;
        dst.initialSeed = src.initialSeed;
        dst.draws = src.draws;
    }
    private function CopyRegistryCardReference(src : CBetaGwentRegistryCardReference, dst : CBetaGwentRegistryCardReference)
    {
    }
    private function CopyRegistryIdStore(src : CBetaGwentRegistryIdStore, dst : CBetaGwentRegistryIdStore)
    {
        var i : int;
        dst.initialized = src.initialized;
        dst.nextId = src.nextId;
        dst.recycled = src.recycled;
        dst.cards = src.cards;
        for (i = 0; i < dst.cards.Size(); i += 1) dst.cards[i] = (CBetaGwentRegistryCardReference)Obj(dst.cards[i]);
    }
    private function CopyRequestStore(src : CBetaGwentRequestStore, dst : CBetaGwentRequestStore)
    {
        var i : int;
        dst.slots = src.slots;
        for (i = 0; i < dst.slots.Size(); i += 1) dst.slots[i] = StructSBetaGwentPendingRequestSlot(dst.slots[i]);
    }
    private function CopyWeatherAI(src : CBetaGwentWeatherAI, dst : CBetaGwentWeatherAI)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
}
