// Generated by tools/build_ai_tuning95.py from data/beta924/ai/tuning95.json.
function BetaGwentAILeaderReserve(round : int) : int {
    if(round<=1)return 12;if(round==2)return 8;return 0;
}
function BetaGwentAILeaderAbilityMinimum(templateId : int) : int {
    switch(templateId) {
    case 200164: return 8;
    default:return 3;
    }
}
function BetaGwentAILeaderUseful(templateId : int, round : int, ownHand : int, body : int, gain : int, setup : int, enemyPassed : bool, deficit : int) : bool {
    if(gain<=0)return false;
    if(enemyPassed && gain>=Max(1,deficit))return true;
    if(ownHand==0 || round>=3)return true;
    if(setup>0 && !enemyPassed)return true;
    if(gain-body<BetaGwentAILeaderAbilityMinimum(templateId))return false;
    if(round==1 && ownHand>=8 && !enemyPassed && gain-body<10)return false;
    return true;
}
function BetaGwentAIOrdinaryPresets(out ids : array<int>) {
    ids.Clear();
    ids.PushBack(54);
    ids.PushBack(55);
    ids.PushBack(56);
    ids.PushBack(57);
    ids.PushBack(58);
    ids.PushBack(59);
    ids.PushBack(60);
    ids.PushBack(61);
    ids.PushBack(62);
    ids.PushBack(94);
    ids.PushBack(63);
    ids.PushBack(95);
    ids.PushBack(64);
    ids.PushBack(65);
    ids.PushBack(66);
    ids.PushBack(67);
    ids.PushBack(68);
    ids.PushBack(69);
    ids.PushBack(70);
    ids.PushBack(71);
    ids.PushBack(72);
    ids.PushBack(73);
    ids.PushBack(74);
    ids.PushBack(75);
    ids.PushBack(76);
    ids.PushBack(77);
    ids.PushBack(78);
    ids.PushBack(79);
    ids.PushBack(80);
    ids.PushBack(81);
    ids.PushBack(82);
    ids.PushBack(83);
    ids.PushBack(96);
    ids.PushBack(84);
    ids.PushBack(85);
    ids.PushBack(86);
    ids.PushBack(87);
    ids.PushBack(88);
    ids.PushBack(89);
    ids.PushBack(90);
    ids.PushBack(91);
    ids.PushBack(97);
    ids.PushBack(98);
    ids.PushBack(99);
    ids.PushBack(92);
    ids.PushBack(93);
}
function BetaGwentAIChooseOrdinaryPreset() : int {
    var manager : CR4GwintManager;var i,j,tmp,picked : int;
    manager=theGame.GetGwintManager();if(!manager)return 54;
    if(manager.betaOrdinaryDeckBag.Size()==0) {
        BetaGwentAIOrdinaryPresets(manager.betaOrdinaryDeckBag);
        for(i=manager.betaOrdinaryDeckBag.Size()-1;i>0;i-=1){
            j=RandRange(i+1);tmp=manager.betaOrdinaryDeckBag[i];
            manager.betaOrdinaryDeckBag[i]=manager.betaOrdinaryDeckBag[j];manager.betaOrdinaryDeckBag[j]=tmp;
        }
        i=manager.betaOrdinaryDeckBag.Size()-1;
        if(i>0 && manager.betaOrdinaryDeckBag[i]==manager.betaOrdinaryLastPreset){
            tmp=manager.betaOrdinaryDeckBag[0];manager.betaOrdinaryDeckBag[0]=manager.betaOrdinaryDeckBag[i];manager.betaOrdinaryDeckBag[i]=tmp;
        }
    }
    i=manager.betaOrdinaryDeckBag.Size()-1;picked=manager.betaOrdinaryDeckBag[i];manager.betaOrdinaryDeckBag.Erase(i);
    manager.betaOrdinaryLastPreset=picked;
    LogChannel('BetaGwent',"DUEL_AI_POOL preset="+picked+" remaining="+manager.betaOrdinaryDeckBag.Size()+" policy=shuffle95");
    return picked;
}
