// Generated by tools/ai/gen_clone.py. Do not edit by hand.
// Deep copy of a duel session for AI lookahead; no visuals are copied.
class CBetaGwentCloner extends IScriptable
{
    private var epoch, head : int;
    private var originals, copies : array<IScriptable>;
    public function CloneSession(source : CBetaGwentDuelSession, stamp : int) : CBetaGwentDuelSession
    {
        var result : CBetaGwentDuelSession;
        epoch = stamp; head = 0; originals.Clear(); copies.Clear();
        result = (CBetaGwentDuelSession)Obj(source);
        while (head < originals.Size()) { CopyAny(originals[head], copies[head]); head += 1; }
        return result;
    }
    public function Obj(o : IScriptable) : IScriptable
    {
        var n : IScriptable;
        var r0 : CBetaGwentActionContext;
        var r1 : CBetaGwentActionServices;
        var r2 : CBetaGwentActionDriver;
        var r3 : CBetaGwentQueuedAction;
        var r4 : CBetaGwentActionSink;
        var r5 : CBetaGwentActionQueue;
        var r6 : CBetaGwentMatchState;
        var r7 : CBetaGwentPowerNumbers;
        var r8 : CBetaGwentRandomGenerator;
        var r9 : CBetaGwentRegistryCardReference;
        var r10 : CBetaGwentRegistryIdStore;
        var r11 : CBetaGwentAbilityContinuation;
        var r12 : CBetaGwentRequestStore;
        var r13 : CBetaGwentCardRequest;
        var r14 : CBetaGwentAIChasePlanner;
        var r15 : CBetaGwentArchetypeAI;
        var r16 : CBetaGwentDuelPassiveFrame;
        var r17 : CBetaGwentDuelEvent;
        var r18 : CBetaGwentDuelEvents;
        var r19 : CBetaGwentDuelMonsters;
        var r20 : CBetaGwentDuelNeutral;
        var r21 : CBetaGwentNilfReaction;
        var r22 : CBetaGwentDuelNilf;
        var r23 : CBetaGwentNilfDependencies;
        var r24 : CBetaGwentDuelNorth;
        var r25 : CBetaGwentDuelScoia;
        var r26 : CBetaGwentDuelSession;
        var r27 : CBetaGwentDuelSkellige;
        var r28 : CBetaGwentDuelSpecials;
        var r29 : CBetaGwentDuelVisualFrame;
        var r30 : CBetaGwentDuelWeather;
        var r31 : CBetaGwentWeatherAI;
        var r32 : CBetaGwentDevelopmentRequestFlow;
        if (!o) return NULL;
        r0 = (CBetaGwentActionContext)o;
        if (r0) { if (r0.bgCloneEpoch == epoch) return r0.bgCloneRef; n = Make(o); r0.bgCloneEpoch = epoch; r0.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r1 = (CBetaGwentActionServices)o;
        if (r1) { if (r1.bgCloneEpoch == epoch) return r1.bgCloneRef; n = Make(o); r1.bgCloneEpoch = epoch; r1.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r2 = (CBetaGwentActionDriver)o;
        if (r2) { if (r2.bgCloneEpoch == epoch) return r2.bgCloneRef; n = Make(o); r2.bgCloneEpoch = epoch; r2.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r3 = (CBetaGwentQueuedAction)o;
        if (r3) { if (r3.bgCloneEpoch == epoch) return r3.bgCloneRef; n = Make(o); r3.bgCloneEpoch = epoch; r3.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r4 = (CBetaGwentActionSink)o;
        if (r4) { if (r4.bgCloneEpoch == epoch) return r4.bgCloneRef; n = Make(o); r4.bgCloneEpoch = epoch; r4.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r5 = (CBetaGwentActionQueue)o;
        if (r5) { if (r5.bgCloneEpoch == epoch) return r5.bgCloneRef; n = Make(o); r5.bgCloneEpoch = epoch; r5.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r6 = (CBetaGwentMatchState)o;
        if (r6) { if (r6.bgCloneEpoch == epoch) return r6.bgCloneRef; n = Make(o); r6.bgCloneEpoch = epoch; r6.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r7 = (CBetaGwentPowerNumbers)o;
        if (r7) { if (r7.bgCloneEpoch == epoch) return r7.bgCloneRef; n = Make(o); r7.bgCloneEpoch = epoch; r7.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r8 = (CBetaGwentRandomGenerator)o;
        if (r8) { if (r8.bgCloneEpoch == epoch) return r8.bgCloneRef; n = Make(o); r8.bgCloneEpoch = epoch; r8.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r9 = (CBetaGwentRegistryCardReference)o;
        if (r9) { if (r9.bgCloneEpoch == epoch) return r9.bgCloneRef; n = Make(o); r9.bgCloneEpoch = epoch; r9.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r10 = (CBetaGwentRegistryIdStore)o;
        if (r10) { if (r10.bgCloneEpoch == epoch) return r10.bgCloneRef; n = Make(o); r10.bgCloneEpoch = epoch; r10.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r11 = (CBetaGwentAbilityContinuation)o;
        if (r11) { if (r11.bgCloneEpoch == epoch) return r11.bgCloneRef; n = Make(o); r11.bgCloneEpoch = epoch; r11.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r12 = (CBetaGwentRequestStore)o;
        if (r12) { if (r12.bgCloneEpoch == epoch) return r12.bgCloneRef; n = Make(o); r12.bgCloneEpoch = epoch; r12.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r13 = (CBetaGwentCardRequest)o;
        if (r13) { if (r13.bgCloneEpoch == epoch) return r13.bgCloneRef; n = Make(o); r13.bgCloneEpoch = epoch; r13.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r14 = (CBetaGwentAIChasePlanner)o;
        if (r14) { if (r14.bgCloneEpoch == epoch) return r14.bgCloneRef; n = Make(o); r14.bgCloneEpoch = epoch; r14.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r15 = (CBetaGwentArchetypeAI)o;
        if (r15) { if (r15.bgCloneEpoch == epoch) return r15.bgCloneRef; n = Make(o); r15.bgCloneEpoch = epoch; r15.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r16 = (CBetaGwentDuelPassiveFrame)o;
        if (r16) { if (r16.bgCloneEpoch == epoch) return r16.bgCloneRef; n = Make(o); r16.bgCloneEpoch = epoch; r16.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r17 = (CBetaGwentDuelEvent)o;
        if (r17) { if (r17.bgCloneEpoch == epoch) return r17.bgCloneRef; n = Make(o); r17.bgCloneEpoch = epoch; r17.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r18 = (CBetaGwentDuelEvents)o;
        if (r18) { if (r18.bgCloneEpoch == epoch) return r18.bgCloneRef; n = Make(o); r18.bgCloneEpoch = epoch; r18.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r19 = (CBetaGwentDuelMonsters)o;
        if (r19) { if (r19.bgCloneEpoch == epoch) return r19.bgCloneRef; n = Make(o); r19.bgCloneEpoch = epoch; r19.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r20 = (CBetaGwentDuelNeutral)o;
        if (r20) { if (r20.bgCloneEpoch == epoch) return r20.bgCloneRef; n = Make(o); r20.bgCloneEpoch = epoch; r20.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r21 = (CBetaGwentNilfReaction)o;
        if (r21) { if (r21.bgCloneEpoch == epoch) return r21.bgCloneRef; n = Make(o); r21.bgCloneEpoch = epoch; r21.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r22 = (CBetaGwentDuelNilf)o;
        if (r22) { if (r22.bgCloneEpoch == epoch) return r22.bgCloneRef; n = Make(o); r22.bgCloneEpoch = epoch; r22.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r23 = (CBetaGwentNilfDependencies)o;
        if (r23) { if (r23.bgCloneEpoch == epoch) return r23.bgCloneRef; n = Make(o); r23.bgCloneEpoch = epoch; r23.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r24 = (CBetaGwentDuelNorth)o;
        if (r24) { if (r24.bgCloneEpoch == epoch) return r24.bgCloneRef; n = Make(o); r24.bgCloneEpoch = epoch; r24.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r25 = (CBetaGwentDuelScoia)o;
        if (r25) { if (r25.bgCloneEpoch == epoch) return r25.bgCloneRef; n = Make(o); r25.bgCloneEpoch = epoch; r25.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r26 = (CBetaGwentDuelSession)o;
        if (r26) { if (r26.bgCloneEpoch == epoch) return r26.bgCloneRef; n = Make(o); r26.bgCloneEpoch = epoch; r26.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r27 = (CBetaGwentDuelSkellige)o;
        if (r27) { if (r27.bgCloneEpoch == epoch) return r27.bgCloneRef; n = Make(o); r27.bgCloneEpoch = epoch; r27.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r28 = (CBetaGwentDuelSpecials)o;
        if (r28) { if (r28.bgCloneEpoch == epoch) return r28.bgCloneRef; n = Make(o); r28.bgCloneEpoch = epoch; r28.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r29 = (CBetaGwentDuelVisualFrame)o;
        if (r29) { if (r29.bgCloneEpoch == epoch) return r29.bgCloneRef; n = Make(o); r29.bgCloneEpoch = epoch; r29.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r30 = (CBetaGwentDuelWeather)o;
        if (r30) { if (r30.bgCloneEpoch == epoch) return r30.bgCloneRef; n = Make(o); r30.bgCloneEpoch = epoch; r30.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r31 = (CBetaGwentWeatherAI)o;
        if (r31) { if (r31.bgCloneEpoch == epoch) return r31.bgCloneRef; n = Make(o); r31.bgCloneEpoch = epoch; r31.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        r32 = (CBetaGwentDevelopmentRequestFlow)o;
        if (r32) { if (r32.bgCloneEpoch == epoch) return r32.bgCloneRef; n = Make(o); r32.bgCloneEpoch = epoch; r32.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }
        return NULL;
    }
    private function Make(o : IScriptable) : IScriptable
    {
        if ((CBetaGwentDuelCreatedCardAction)o) return new CBetaGwentDuelCreatedCardAction in this;
        if ((CBetaGwentDuelEffectAction)o) return new CBetaGwentDuelEffectAction in this;
        if ((CBetaGwentDuelMoveAction)o) return new CBetaGwentDuelMoveAction in this;
        if ((CBetaGwentDuelRelocateAction)o) return new CBetaGwentDuelRelocateAction in this;
        if ((CBetaGwentDuelSpawnAction)o) return new CBetaGwentDuelSpawnAction in this;
        if ((CBetaGwentDuelTimerAction)o) return new CBetaGwentDuelTimerAction in this;
        if ((CBetaGwentMonsterDuelAction)o) return new CBetaGwentMonsterDuelAction in this;
        if ((CBetaGwentActionManager)o) return new CBetaGwentActionManager in this;
        if ((CBetaGwentDuelActionServices)o) return new CBetaGwentDuelActionServices in this;
        if ((CBetaGwentDuelCard)o) return new CBetaGwentDuelCard in this;
        if ((CBetaGwentDuelEffectRuntime)o) return new CBetaGwentDuelEffectRuntime in this;
        if ((CBetaGwentDuelPower)o) return new CBetaGwentDuelPower in this;
        if ((CBetaGwentDuelRegistry)o) return new CBetaGwentDuelRegistry in this;
        if ((CBetaGwentManagerContext)o) return new CBetaGwentManagerContext in this;
        if ((CBetaGwentAIChasePlanner)o) return new CBetaGwentAIChasePlanner in this;
        if ((CBetaGwentAbilityContinuation)o) return new CBetaGwentAbilityContinuation in this;
        if ((CBetaGwentActionContext)o) return new CBetaGwentActionContext in this;
        if ((CBetaGwentActionDriver)o) return new CBetaGwentActionDriver in this;
        if ((CBetaGwentActionQueue)o) return new CBetaGwentActionQueue in this;
        if ((CBetaGwentArchetypeAI)o) return new CBetaGwentArchetypeAI in this;
        if ((CBetaGwentCardRequest)o) return new CBetaGwentCardRequest in this;
        if ((CBetaGwentDevelopmentRequestFlow)o) return new CBetaGwentDevelopmentRequestFlow in this;
        if ((CBetaGwentDuelEvent)o) return new CBetaGwentDuelEvent in this;
        if ((CBetaGwentDuelEvents)o) return new CBetaGwentDuelEvents in this;
        if ((CBetaGwentDuelMonsters)o) return new CBetaGwentDuelMonsters in this;
        if ((CBetaGwentDuelNeutral)o) return new CBetaGwentDuelNeutral in this;
        if ((CBetaGwentDuelNilf)o) return new CBetaGwentDuelNilf in this;
        if ((CBetaGwentDuelNorth)o) return new CBetaGwentDuelNorth in this;
        if ((CBetaGwentDuelPassiveFrame)o) return new CBetaGwentDuelPassiveFrame in this;
        if ((CBetaGwentDuelScoia)o) return new CBetaGwentDuelScoia in this;
        if ((CBetaGwentDuelSession)o) return new CBetaGwentDuelSession in this;
        if ((CBetaGwentDuelSkellige)o) return new CBetaGwentDuelSkellige in this;
        if ((CBetaGwentDuelSpecials)o) return new CBetaGwentDuelSpecials in this;
        if ((CBetaGwentDuelVisualFrame)o) return new CBetaGwentDuelVisualFrame in this;
        if ((CBetaGwentDuelWeather)o) return new CBetaGwentDuelWeather in this;
        if ((CBetaGwentMatchState)o) return new CBetaGwentMatchState in this;
        if ((CBetaGwentNilfDependencies)o) return new CBetaGwentNilfDependencies in this;
        if ((CBetaGwentNilfReaction)o) return new CBetaGwentNilfReaction in this;
        if ((CBetaGwentQueuedAction)o) return new CBetaGwentQueuedAction in this;
        if ((CBetaGwentRandomGenerator)o) return new CBetaGwentRandomGenerator in this;
        if ((CBetaGwentRegistryCardReference)o) return new CBetaGwentRegistryCardReference in this;
        if ((CBetaGwentRegistryIdStore)o) return new CBetaGwentRegistryIdStore in this;
        if ((CBetaGwentRequestStore)o) return new CBetaGwentRequestStore in this;
        if ((CBetaGwentWeatherAI)o) return new CBetaGwentWeatherAI in this;
        return NULL;
    }
    private function CopyAny(src : IScriptable, dst : IScriptable)
    {
        if ((CBetaGwentDuelCreatedCardAction)src) { CopyDuelCreatedCardAction((CBetaGwentDuelCreatedCardAction)src, (CBetaGwentDuelCreatedCardAction)dst); return; }
        if ((CBetaGwentDuelEffectAction)src) { CopyDuelEffectAction((CBetaGwentDuelEffectAction)src, (CBetaGwentDuelEffectAction)dst); return; }
        if ((CBetaGwentDuelMoveAction)src) { CopyDuelMoveAction((CBetaGwentDuelMoveAction)src, (CBetaGwentDuelMoveAction)dst); return; }
        if ((CBetaGwentDuelRelocateAction)src) { CopyDuelRelocateAction((CBetaGwentDuelRelocateAction)src, (CBetaGwentDuelRelocateAction)dst); return; }
        if ((CBetaGwentDuelSpawnAction)src) { CopyDuelSpawnAction((CBetaGwentDuelSpawnAction)src, (CBetaGwentDuelSpawnAction)dst); return; }
        if ((CBetaGwentDuelTimerAction)src) { CopyDuelTimerAction((CBetaGwentDuelTimerAction)src, (CBetaGwentDuelTimerAction)dst); return; }
        if ((CBetaGwentMonsterDuelAction)src) { CopyMonsterDuelAction((CBetaGwentMonsterDuelAction)src, (CBetaGwentMonsterDuelAction)dst); return; }
        if ((CBetaGwentActionManager)src) { CopyActionManager((CBetaGwentActionManager)src, (CBetaGwentActionManager)dst); return; }
        if ((CBetaGwentDuelActionServices)src) { CopyDuelActionServices((CBetaGwentDuelActionServices)src, (CBetaGwentDuelActionServices)dst); return; }
        if ((CBetaGwentDuelCard)src) { CopyDuelCard((CBetaGwentDuelCard)src, (CBetaGwentDuelCard)dst); return; }
        if ((CBetaGwentDuelEffectRuntime)src) { CopyDuelEffectRuntime((CBetaGwentDuelEffectRuntime)src, (CBetaGwentDuelEffectRuntime)dst); return; }
        if ((CBetaGwentDuelPower)src) { CopyDuelPower((CBetaGwentDuelPower)src, (CBetaGwentDuelPower)dst); return; }
        if ((CBetaGwentDuelRegistry)src) { CopyDuelRegistry((CBetaGwentDuelRegistry)src, (CBetaGwentDuelRegistry)dst); return; }
        if ((CBetaGwentManagerContext)src) { CopyManagerContext((CBetaGwentManagerContext)src, (CBetaGwentManagerContext)dst); return; }
        if ((CBetaGwentAIChasePlanner)src) { CopyAIChasePlanner((CBetaGwentAIChasePlanner)src, (CBetaGwentAIChasePlanner)dst); return; }
        if ((CBetaGwentAbilityContinuation)src) { CopyAbilityContinuation((CBetaGwentAbilityContinuation)src, (CBetaGwentAbilityContinuation)dst); return; }
        if ((CBetaGwentActionContext)src) { CopyActionContext((CBetaGwentActionContext)src, (CBetaGwentActionContext)dst); return; }
        if ((CBetaGwentActionDriver)src) { CopyActionDriver((CBetaGwentActionDriver)src, (CBetaGwentActionDriver)dst); return; }
        if ((CBetaGwentActionQueue)src) { CopyActionQueue((CBetaGwentActionQueue)src, (CBetaGwentActionQueue)dst); return; }
        if ((CBetaGwentArchetypeAI)src) { CopyArchetypeAI((CBetaGwentArchetypeAI)src, (CBetaGwentArchetypeAI)dst); return; }
        if ((CBetaGwentCardRequest)src) { CopyCardRequest((CBetaGwentCardRequest)src, (CBetaGwentCardRequest)dst); return; }
        if ((CBetaGwentDevelopmentRequestFlow)src) { CopyDevelopmentRequestFlow((CBetaGwentDevelopmentRequestFlow)src, (CBetaGwentDevelopmentRequestFlow)dst); return; }
        if ((CBetaGwentDuelEvent)src) { CopyDuelEvent((CBetaGwentDuelEvent)src, (CBetaGwentDuelEvent)dst); return; }
        if ((CBetaGwentDuelEvents)src) { CopyDuelEvents((CBetaGwentDuelEvents)src, (CBetaGwentDuelEvents)dst); return; }
        if ((CBetaGwentDuelMonsters)src) { CopyDuelMonsters((CBetaGwentDuelMonsters)src, (CBetaGwentDuelMonsters)dst); return; }
        if ((CBetaGwentDuelNeutral)src) { CopyDuelNeutral((CBetaGwentDuelNeutral)src, (CBetaGwentDuelNeutral)dst); return; }
        if ((CBetaGwentDuelNilf)src) { CopyDuelNilf((CBetaGwentDuelNilf)src, (CBetaGwentDuelNilf)dst); return; }
        if ((CBetaGwentDuelNorth)src) { CopyDuelNorth((CBetaGwentDuelNorth)src, (CBetaGwentDuelNorth)dst); return; }
        if ((CBetaGwentDuelPassiveFrame)src) { CopyDuelPassiveFrame((CBetaGwentDuelPassiveFrame)src, (CBetaGwentDuelPassiveFrame)dst); return; }
        if ((CBetaGwentDuelScoia)src) { CopyDuelScoia((CBetaGwentDuelScoia)src, (CBetaGwentDuelScoia)dst); return; }
        if ((CBetaGwentDuelSession)src) { CopyDuelSession((CBetaGwentDuelSession)src, (CBetaGwentDuelSession)dst); return; }
        if ((CBetaGwentDuelSkellige)src) { CopyDuelSkellige((CBetaGwentDuelSkellige)src, (CBetaGwentDuelSkellige)dst); return; }
        if ((CBetaGwentDuelSpecials)src) { CopyDuelSpecials((CBetaGwentDuelSpecials)src, (CBetaGwentDuelSpecials)dst); return; }
        if ((CBetaGwentDuelVisualFrame)src) { CopyDuelVisualFrame((CBetaGwentDuelVisualFrame)src, (CBetaGwentDuelVisualFrame)dst); return; }
        if ((CBetaGwentDuelWeather)src) { CopyDuelWeather((CBetaGwentDuelWeather)src, (CBetaGwentDuelWeather)dst); return; }
        if ((CBetaGwentMatchState)src) { CopyMatchState((CBetaGwentMatchState)src, (CBetaGwentMatchState)dst); return; }
        if ((CBetaGwentNilfDependencies)src) { CopyNilfDependencies((CBetaGwentNilfDependencies)src, (CBetaGwentNilfDependencies)dst); return; }
        if ((CBetaGwentNilfReaction)src) { CopyNilfReaction((CBetaGwentNilfReaction)src, (CBetaGwentNilfReaction)dst); return; }
        if ((CBetaGwentQueuedAction)src) { CopyQueuedAction((CBetaGwentQueuedAction)src, (CBetaGwentQueuedAction)dst); return; }
        if ((CBetaGwentRandomGenerator)src) { CopyRandomGenerator((CBetaGwentRandomGenerator)src, (CBetaGwentRandomGenerator)dst); return; }
        if ((CBetaGwentRegistryCardReference)src) { CopyRegistryCardReference((CBetaGwentRegistryCardReference)src, (CBetaGwentRegistryCardReference)dst); return; }
        if ((CBetaGwentRegistryIdStore)src) { CopyRegistryIdStore((CBetaGwentRegistryIdStore)src, (CBetaGwentRegistryIdStore)dst); return; }
        if ((CBetaGwentRequestStore)src) { CopyRequestStore((CBetaGwentRequestStore)src, (CBetaGwentRequestStore)dst); return; }
        if ((CBetaGwentWeatherAI)src) { CopyWeatherAI((CBetaGwentWeatherAI)src, (CBetaGwentWeatherAI)dst); return; }
    }
    private function CopyDuelCreatedCardAction(src : CBetaGwentDuelCreatedCardAction, dst : CBetaGwentDuelCreatedCardAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.templateId = src.templateId;
        dst.instanceId = src.instanceId;
    }
    private function CopyDuelEffectAction(src : CBetaGwentDuelEffectAction, dst : CBetaGwentDuelEffectAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.attacker = (CBetaGwentDuelCard)Obj(src.attacker);
        dst.target = (CBetaGwentDuelCard)Obj(src.target);
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.operation = src.operation;
        dst.amount = src.amount;
        dst.allowedLocations = src.allowedLocations;
        dst.ignoreArmor = src.ignoreArmor;
        dst.attackId = src.attackId;
    }
    private function CopyDuelMoveAction(src : CBetaGwentDuelMoveAction, dst : CBetaGwentDuelMoveAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.destination = src.destination;
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
    }
    private function CopyDuelRelocateAction(src : CBetaGwentDuelRelocateAction, dst : CBetaGwentDuelRelocateAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
        dst.side = src.side;
        dst.row = src.row;
        dst.resetHand = src.resetHand;
    }
    private function CopyDuelSpawnAction(src : CBetaGwentDuelSpawnAction, dst : CBetaGwentDuelSpawnAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.fromPosition = src.fromPosition;
        dst.templateId = src.templateId;
        dst.ids = src.ids;
    }
    private function CopyDuelTimerAction(src : CBetaGwentDuelTimerAction, dst : CBetaGwentDuelTimerAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
        dst.operation = src.operation;
        dst.value = src.value;
    }
    private function CopyMonsterDuelAction(src : CBetaGwentMonsterDuelAction, dst : CBetaGwentMonsterDuelAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
        dst.prepared = src.prepared;
        dst.context = (CBetaGwentActionContext)Obj(src.context);
        dst.networkId = src.networkId;
        dst.delay = src.delay;
        dst.stateChanging = src.stateChanging;
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.target = (CBetaGwentDuelCard)Obj(src.target);
        dst.retaliation = src.retaliation;
        dst.heal = src.heal;
        dst.armor = src.armor;
    }
    private function CopyActionManager(src : CBetaGwentActionManager, dst : CBetaGwentActionManager)
    {
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.services = (CBetaGwentActionServices)Obj(src.services);
        dst.initialized = src.initialized;
        dst.lastKnownNetworkId = src.lastKnownNetworkId;
        dst.fault = src.fault;
        dst.dispatches = src.dispatches;
    }
    private function CopyDuelActionServices(src : CBetaGwentDuelActionServices, dst : CBetaGwentDuelActionServices)
    {
        dst.runtime = (CBetaGwentDuelEffectRuntime)Obj(src.runtime);
    }
    private function CopyDuelCard(src : CBetaGwentDuelCard, dst : CBetaGwentDuelCard)
    {
        dst.cardState = src.cardState;
        dst.definition = src.definition;
        dst.power = (CBetaGwentDuelPower)Obj(src.power);
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.consumeAttackerId = src.consumeAttackerId;
        dst.playedChild = (CBetaGwentDuelCard)Obj(src.playedChild);
        dst.monsterStage = src.monsterStage;
        dst.monsterRemaining = src.monsterRemaining;
        dst.monsterStored = src.monsterStored;
        dst.monsterOnce = src.monsterOnce;
        dst.playFromLocation = src.playFromLocation;
        dst.lastActiveRow = src.lastActiveRow;
        dst.northernCrew = src.northernCrew;
        dst.nilfCounter = src.nilfCounter;
        dst.neutralChoice = src.neutralChoice;
        dst.createdCopy = src.createdCopy;
        dst.monsterIds = src.monsterIds;
        dst.selectedModeId = src.selectedModeId;
    }
    private function CopyDuelEffectRuntime(src : CBetaGwentDuelEffectRuntime, dst : CBetaGwentDuelEffectRuntime)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.queue = (CBetaGwentActionQueue)Obj(src.queue);
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.manager = (CBetaGwentActionManager)Obj(src.manager);
        dst.services = (CBetaGwentDuelActionServices)Obj(src.services);
        dst.frames.Clear(); for (i = 0; i < src.frames.Size(); i += 1) dst.frames.PushBack((CBetaGwentDuelPassiveFrame)Obj(src.frames[i]));
        dst.buildingFrame = (CBetaGwentDuelPassiveFrame)Obj(src.buildingFrame);
        dst.dispatchingFrame = (CBetaGwentDuelPassiveFrame)Obj(src.dispatchingFrame);
        dst.passiveCount = src.passiveCount;
        dst.maximumDepth = src.maximumDepth;
        dst.failed = src.failed;
        dst.running = src.running;
        dst.beforeCount = src.beforeCount;
        dst.appliedCount = src.appliedCount;
        dst.afterCount = src.afterCount;
        dst.skippedCount = src.skippedCount;
        dst.attackSerial = src.attackSerial;
        dst.attackKey = src.attackKey;
        dst.attackSource = (CBetaGwentDuelCard)Obj(src.attackSource);
        dst.attackOpen = src.attackOpen;
    }
    private function CopyDuelPower(src : CBetaGwentDuelPower, dst : CBetaGwentDuelPower)
    {
        dst.initialized = src.initialized;
        dst.basePower = src.basePower;
        dst.permanentPower = src.permanentPower;
        dst.currentPower = src.currentPower;
        dst.currentArmor = src.currentArmor;
        dst.card = (CBetaGwentDuelCard)Obj(src.card);
    }
    private function CopyDuelRegistry(src : CBetaGwentDuelRegistry, dst : CBetaGwentDuelRegistry)
    {
        var i : int;
        dst.initialized = src.initialized;
        dst.nextId = src.nextId;
        dst.recycled = src.recycled;
        dst.cards.Clear(); for (i = 0; i < src.cards.Size(); i += 1) dst.cards.PushBack((CBetaGwentRegistryCardReference)Obj(src.cards[i]));
    }
    private function CopyManagerContext(src : CBetaGwentManagerContext, dst : CBetaGwentManagerContext)
    {
        dst.authority = src.authority;
        dst.mainController = src.mainController;
        dst.verbose = src.verbose;
        dst.dirty = src.dirty;
    }
    private function CopyAIChasePlanner(src : CBetaGwentAIChasePlanner, dst : CBetaGwentAIChasePlanner)
    {
    }
    private function CopyAbilityContinuation(src : CBetaGwentAbilityContinuation, dst : CBetaGwentAbilityContinuation)
    {
        dst.ownerInstanceId = src.ownerInstanceId;
        dst.nodeId = src.nodeId;
        dst.nodeSetup = src.nodeSetup;
        dst.completedNodes = src.completedNodes;
        dst.phase = src.phase;
        dst.pending = (CBetaGwentCardRequest)Obj(src.pending);
    }
    private function CopyActionContext(src : CBetaGwentActionContext, dst : CBetaGwentActionContext)
    {
        dst.authority = src.authority;
    }
    private function CopyActionDriver(src : CBetaGwentActionDriver, dst : CBetaGwentActionDriver)
    {
        dst.context = (CBetaGwentManagerContext)Obj(src.context);
        dst.manager = (CBetaGwentActionManager)Obj(src.manager);
        dst.queue = (CBetaGwentActionQueue)Obj(src.queue);
    }
    private function CopyActionQueue(src : CBetaGwentActionQueue, dst : CBetaGwentActionQueue)
    {
        var i : int;
        dst.actions.Clear(); for (i = 0; i < src.actions.Size(); i += 1) dst.actions.PushBack((CBetaGwentQueuedAction)Obj(src.actions[i]));
        dst.sink = (CBetaGwentActionSink)Obj(src.sink);
        dst.initialized = src.initialized;
        dst.authority = src.authority;
        dst.authorityContext = (CBetaGwentActionContext)Obj(src.authorityContext);
        dst.abilityLocal = src.abilityLocal;
    }
    private function CopyArchetypeAI(src : CBetaGwentArchetypeAI, dst : CBetaGwentArchetypeAI)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.profile = src.profile;
        dst.family = src.family;
        dst.pairs = src.pairs;
        dst.hand.Clear(); for (i = 0; i < src.hand.Size(); i += 1) dst.hand.PushBack((CBetaGwentDuelCard)Obj(src.hand[i]));
        dst.board.Clear(); for (i = 0; i < src.board.Size(); i += 1) dst.board.PushBack((CBetaGwentDuelCard)Obj(src.board[i]));
        dst.situation = src.situation;
    }
    private function CopyCardRequest(src : CBetaGwentCardRequest, dst : CBetaGwentCardRequest)
    {
        dst.requestState = src.requestState;
        dst.choices = src.choices;
        dst.validTargets = src.validTargets;
        dst.selected = src.selected;
        dst.targetsInShape = src.targetsInShape;
    }
    private function CopyDevelopmentRequestFlow(src : CBetaGwentDevelopmentRequestFlow, dst : CBetaGwentDevelopmentRequestFlow)
    {
        dst.pending = (CBetaGwentCardRequest)Obj(src.pending);
        dst.continuation = (CBetaGwentAbilityContinuation)Obj(src.continuation);
        dst.store = (CBetaGwentRequestStore)Obj(src.store);
        dst.nextRequestId = src.nextRequestId;
        dst.completed = src.completed;
        dst.aborted = src.aborted;
        dst.sourceCards = src.sourceCards;
        dst.lastResult = src.lastResult;
        dst.message = src.message;
        dst.isolatedCheck = src.isolatedCheck;
    }
    private function CopyDuelEvent(src : CBetaGwentDuelEvent, dst : CBetaGwentDuelEvent)
    {
        dst.kind = src.kind;
        dst.batchSerial = src.batchSerial;
        dst.source = src.source;
        dst.cause = src.cause;
        dst.rowToken = src.rowToken;
        dst.rowTargets = src.rowTargets;
        dst.banishedConsume = src.banishedConsume;
    }
    private function CopyDuelEvents(src : CBetaGwentDuelEvents, dst : CBetaGwentDuelEvents)
    {
        var i : int;
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.pending.Clear(); for (i = 0; i < src.pending.Size(); i += 1) dst.pending.PushBack((CBetaGwentDuelEvent)Obj(src.pending[i]));
        dst.batchSerial = src.batchSerial;
    }
    private function CopyDuelMonsters(src : CBetaGwentDuelMonsters, dst : CBetaGwentDuelMonsters)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.north = (CBetaGwentDuelNorth)Obj(src.north);
        dst.nilf = (CBetaGwentDuelNilf)Obj(src.nilf);
        dst.neutral = (CBetaGwentDuelNeutral)Obj(src.neutral);
        dst.skellige = (CBetaGwentDuelSkellige)Obj(src.skellige);
        dst.scoia = (CBetaGwentDuelScoia)Obj(src.scoia);
    }
    private function CopyDuelNeutral(src : CBetaGwentDuelNeutral, dst : CBetaGwentDuelNeutral)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
    private function CopyDuelNilf(src : CBetaGwentDuelNilf, dst : CBetaGwentDuelNilf)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.dependencies = (CBetaGwentNilfDependencies)Obj(src.dependencies);
    }
    private function CopyDuelNorth(src : CBetaGwentDuelNorth, dst : CBetaGwentDuelNorth)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
    private function CopyDuelPassiveFrame(src : CBetaGwentDuelPassiveFrame, dst : CBetaGwentDuelPassiveFrame)
    {
        dst.actions = (CBetaGwentActionQueue)Obj(src.actions);
        dst.source = src.source;
        dst.batchSerial = src.batchSerial;
    }
    private function CopyDuelScoia(src : CBetaGwentDuelScoia, dst : CBetaGwentDuelScoia)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.historyOne = src.historyOne;
        dst.historyTwo = src.historyTwo;
    }
    private function CopyDuelSession(src : CBetaGwentDuelSession, dst : CBetaGwentDuelSession)
    {
        var i : int;
        dst.events = (CBetaGwentDuelEvents)Obj(src.events);
        dst.drainingDeaths = src.drainingDeaths;
        dst.effects = (CBetaGwentDuelEffectRuntime)Obj(src.effects);
        dst.playStack.Clear(); for (i = 0; i < src.playStack.Size(); i += 1) dst.playStack.PushBack((CBetaGwentDuelCard)Obj(src.playStack[i]));
        dst.match = (CBetaGwentMatchState)Obj(src.match);
        dst.registry = (CBetaGwentDuelRegistry)Obj(src.registry);
        dst.live.Clear(); for (i = 0; i < src.live.Size(); i += 1) dst.live.PushBack((CBetaGwentDuelCard)Obj(src.live[i]));
        dst.dying.Clear(); for (i = 0; i < src.dying.Size(); i += 1) dst.dying.PushBack((CBetaGwentDuelCard)Obj(src.dying[i]));
        dst.pendingConsumeVisuals = src.pendingConsumeVisuals;
        dst.message = src.message;
        dst.waiting = src.waiting;
        dst.fatal = src.fatal;
        dst.pendingCard = (CBetaGwentDuelCard)Obj(src.pendingCard);
        dst.pendingLeader = (CBetaGwentDuelCard)Obj(src.pendingLeader);
        dst.pendingRally = (CBetaGwentDuelCard)Obj(src.pendingRally);
        dst.pendingChoice = src.pendingChoice;
        dst.weather = (CBetaGwentDuelWeather)Obj(src.weather);
        dst.specials = (CBetaGwentDuelSpecials)Obj(src.specials);
        dst.monsters = (CBetaGwentDuelMonsters)Obj(src.monsters);
        dst.monsterMinimum = src.monsterMinimum;
        dst.monsterMaximum = src.monsterMaximum;
        dst.specialHitsLeft = src.specialHitsLeft;
        dst.handPowerTarget = src.handPowerTarget;
        dst.pendingHandPower = src.pendingHandPower;
        dst.pendingPileChoice = src.pendingPileChoice;
        dst.pendingIds = src.pendingIds;
        dst.requestId = src.requestId;
        dst.pendingRow = src.pendingRow;
        dst.random = (CBetaGwentRandomGenerator)Obj(src.random);
        dst.mulligan = src.mulligan;
        dst.mulliganBudget = src.mulliganBudget;
        dst.mulliganUsed = src.mulliganUsed;
        dst.roundStarter = src.roundStarter;
        dst.blacklistedTemplates = src.blacklistedTemplates;
        dst.reservedCards = src.reservedCards;
        dst.visualFrames.Clear();
        dst.recordVisuals = src.recordVisuals;
        dst.visualOverflow = src.visualOverflow;
        dst.visualSourceId = src.visualSourceId;
        dst.visualTemplateId = src.visualTemplateId;
        dst.visualSide = src.visualSide;
        dst.visualRow = src.visualRow;
        dst.visualAttack = src.visualAttack;
        dst.presetOne = src.presetOne;
        dst.presetTwo = src.presetTwo;
        dst.leaderTemplateOne = src.leaderTemplateOne;
        dst.leaderTemplateTwo = src.leaderTemplateTwo;
        dst.nilfJobs.Clear(); for (i = 0; i < src.nilfJobs.Size(); i += 1) dst.nilfJobs.PushBack((CBetaGwentNilfReaction)Obj(src.nilfJobs[i]));
        dst.nilfJob = (CBetaGwentNilfReaction)Obj(src.nilfJob);
        dst.nilfEndingTurn = src.nilfEndingTurn;
        dst.mulliganReactions = src.mulliganReactions;
        dst.nilfInitialOne = src.nilfInitialOne;
        dst.nilfInitialTwo = src.nilfInitialTwo;
        dst.nilfSpellOne = src.nilfSpellOne;
        dst.nilfSpellTwo = src.nilfSpellTwo;
        dst.nilfLastMovedUnit = src.nilfLastMovedUnit;
        dst.weatherAI = (CBetaGwentWeatherAI)Obj(src.weatherAI);
        dst.weatherProfile = src.weatherProfile;
        dst.archetypeAI = (CBetaGwentArchetypeAI)Obj(src.archetypeAI);
        dst.aiChaseRound = src.aiChaseRound;
        dst.aiChaseInitialHand = src.aiChaseInitialHand;
        dst.aiObservedRound = src.aiObservedRound;
        dst.aiObservedEnemyScore = src.aiObservedEnemyScore;
        dst.aiPublicTempo = src.aiPublicTempo;
        dst.aiRoundHandOne = src.aiRoundHandOne;
        dst.aiRoundHandTwo = src.aiRoundHandTwo;
        dst.aiPlacing = src.aiPlacing;
        dst.aiSimulating = src.aiSimulating;
        dst.aiCloneEpoch = src.aiCloneEpoch;
        dst.aiSimCloner = src.aiSimCloner;
        dst.aiSimDamp = src.aiSimDamp;
        dst.effectSourceDepth = src.effectSourceDepth;
        dst.savedSourceId = src.savedSourceId;
        dst.savedSourceTemplate = src.savedSourceTemplate;
        dst.savedSourceSide = src.savedSourceSide;
        dst.savedSourceRow = src.savedSourceRow;
    }
    private function CopyDuelSkellige(src : CBetaGwentDuelSkellige, dst : CBetaGwentDuelSkellige)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.beastsOne = src.beastsOne;
        dst.beastsTwo = src.beastsTwo;
    }
    private function CopyDuelSpecials(src : CBetaGwentDuelSpecials, dst : CBetaGwentDuelSpecials)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.weather = (CBetaGwentDuelWeather)Obj(src.weather);
    }
    private function CopyDuelVisualFrame(src : CBetaGwentDuelVisualFrame, dst : CBetaGwentDuelVisualFrame)
    {
        dst.matchState = src.matchState;
        dst.cards = src.cards;
        dst.weatherTokens = src.weatherTokens;
        dst.weatherDamage = src.weatherDamage;
        dst.scoreOne = src.scoreOne;
        dst.scoreTwo = src.scoreTwo;
        dst.flags = src.flags;
        dst.enemyHand = src.enemyHand;
        dst.graveOne = src.graveOne;
        dst.graveTwo = src.graveTwo;
        dst.deckOne = src.deckOne;
        dst.deckTwo = src.deckTwo;
        dst.leaderOne = src.leaderOne;
        dst.leaderTwo = src.leaderTwo;
        dst.status = src.status;
        dst.kind = src.kind;
        dst.sourceId = src.sourceId;
        dst.targetId = src.targetId;
        dst.side = src.side;
        dst.row = src.row;
        dst.templateId = src.templateId;
        dst.duration = src.duration;
        dst.targetTemplateId = src.targetTemplateId;
        dst.targetPower = src.targetPower;
        dst.targetSide = src.targetSide;
        dst.targetZone = src.targetZone;
        dst.audioKind = src.audioKind;
        dst.attackId = src.attackId;
        dst.attackCount = src.attackCount;
    }
    private function CopyDuelWeather(src : CBetaGwentDuelWeather, dst : CBetaGwentDuelWeather)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.hazards = src.hazards;
        dst.dreamRows = src.dreamRows;
    }
    private function CopyMatchState(src : CBetaGwentMatchState, dst : CBetaGwentMatchState)
    {
        dst.initialized = src.initialized;
        dst.playerOne = src.playerOne;
        dst.playerTwo = src.playerTwo;
        dst.roundNumber = src.roundNumber;
        dst.turnSequence = src.turnSequence;
        dst.startingPlayerId = src.startingPlayerId;
        dst.currentPlayerId = src.currentPlayerId;
        dst.roundActive = src.roundActive;
        dst.turnActive = src.turnActive;
        dst.results = src.results;
    }
    private function CopyNilfDependencies(src : CBetaGwentNilfDependencies, dst : CBetaGwentNilfDependencies)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
        dst.nilf = (CBetaGwentDuelNilf)Obj(src.nilf);
    }
    private function CopyNilfReaction(src : CBetaGwentNilfReaction, dst : CBetaGwentNilfReaction)
    {
        dst.source = (CBetaGwentDuelCard)Obj(src.source);
        dst.kind = src.kind;
        dst.side = src.side;
    }
    private function CopyQueuedAction(src : CBetaGwentQueuedAction, dst : CBetaGwentQueuedAction)
    {
        dst.fireTriggers = src.fireTriggers;
        dst.beforeFired = src.beforeFired;
        dst.priorityAction = src.priorityAction;
    }
    private function CopyRandomGenerator(src : CBetaGwentRandomGenerator, dst : CBetaGwentRandomGenerator)
    {
        dst.words = src.words;
        dst.remaining = src.remaining;
        dst.cursor = src.cursor;
        dst.reseedValue = src.reseedValue;
        dst.initialSeed = src.initialSeed;
        dst.draws = src.draws;
    }
    private function CopyRegistryCardReference(src : CBetaGwentRegistryCardReference, dst : CBetaGwentRegistryCardReference)
    {
    }
    private function CopyRegistryIdStore(src : CBetaGwentRegistryIdStore, dst : CBetaGwentRegistryIdStore)
    {
        var i : int;
        dst.initialized = src.initialized;
        dst.nextId = src.nextId;
        dst.recycled = src.recycled;
        dst.cards.Clear(); for (i = 0; i < src.cards.Size(); i += 1) dst.cards.PushBack((CBetaGwentRegistryCardReference)Obj(src.cards[i]));
    }
    private function CopyRequestStore(src : CBetaGwentRequestStore, dst : CBetaGwentRequestStore)
    {
        var i : int;
        var slotSBetaGwentPendingRequestSlot : SBetaGwentPendingRequestSlot;
        dst.slots = src.slots;
        for (i = 0; i < dst.slots.Size(); i += 1) { slotSBetaGwentPendingRequestSlot = dst.slots[i]; slotSBetaGwentPendingRequestSlot.request = (CBetaGwentCardRequest)Obj(slotSBetaGwentPendingRequestSlot.request); slotSBetaGwentPendingRequestSlot.continuation = (CBetaGwentAbilityContinuation)Obj(slotSBetaGwentPendingRequestSlot.continuation); dst.slots[i] = slotSBetaGwentPendingRequestSlot; }
    }
    private function CopyWeatherAI(src : CBetaGwentWeatherAI, dst : CBetaGwentWeatherAI)
    {
        dst.game = (CBetaGwentDuelSession)Obj(src.game);
    }
}
