// Generated by tools/build_progression.py; native names validated from stock XML.
function BetaGwentStarterRevision() : int { return 2; }
function BetaGwentStarterPreset(faction : int) : int {
    switch(faction) {
    case 2: return 16;
    case 8: return 17;
    case 4: return 18;
    case 16: return 19;
    case 32: return 20;
    default: return 16;
    }
}
function BetaGwentQuestGold(deck : name) : int {
    switch(deck) {
    case 'Baron': return 122101;
    case 'Roche': return 122102;
    case 'Dijkstra': return 122105;
    case 'Zoltan': return 142105;
    case 'Lambert': return 200235;
    case 'Thaler': return 112103;
    case 'VimmeVivaldi': return 200080;
    case 'ScoiaTrader': return 142103;
    case 'Stjepan': return 112106;
    case 'CrossroadsInnkeeper': return 112108;
    case 'Olivier': return 112112;
    case 'BoatBuilder': return 132102;
    case 'CardProdigy': return 131102;
    case 'Hermit': return 132103;
    case 'Sjusta': return 142101;
    case 'Gremista': return 152107;
    case 'Crach': return 152101;
    case 'LugosTheMad': return 152106;
    case 'Mousesack': return 152103;
    case 'MarkizaSerenity': return 142104;
    case 'Shani': return 122106;
    case 'Olgierd': return 132215;
    case 'Gambler': return 112107;
    case 'Halflings': return 132107;
    case 'CircusGwentAddict': return 200209;
    case 'NKTournament': return 201618;
    case 'NilfTournament': return 162104;
    case 'ScoiaTournament': return 142102;
    case 'NMLTournament': return 132104;
    case 'NMLTournament2': return 132101;
    case 'NilfTournament2': return 162103;
    case 'SkelTournament2': return 152104;
    case 'ScoiaTournament2': return 142106;
    default: return 0;
    }
}
function BetaGwentQuestPreset(deck : name) : int {
    switch(deck) {
    case 'Baron': return 22;
    case 'Roche': return 21;
    case 'Dijkstra': return 23;
    case 'Zoltan': return 24;
    case 'Lambert': return 25;
    case 'Thaler': return 26;
    case 'VimmeVivaldi': return 27;
    case 'ScoiaTrader': return 28;
    case 'Stjepan': return 29;
    case 'CrossroadsInnkeeper': return 30;
    case 'Olivier': return 31;
    case 'BoatBuilder': return 32;
    case 'CardProdigy': return 33;
    case 'Hermit': return 34;
    case 'Sjusta': return 35;
    case 'Gremista': return 36;
    case 'Crach': return 37;
    case 'LugosTheMad': return 38;
    case 'Mousesack': return 39;
    case 'MarkizaSerenity': return 40;
    case 'Shani': return 41;
    case 'Olgierd': return 42;
    case 'Gambler': return 43;
    case 'Halflings': return 44;
    case 'CircusGwentAddict': return 45;
    case 'NKTournament': return 46;
    case 'NilfTournament': return 47;
    case 'ScoiaTournament': return 48;
    case 'NMLTournament': return 49;
    case 'NMLTournament2': return 50;
    case 'NilfTournament2': return 51;
    case 'SkelTournament2': return 52;
    case 'ScoiaTournament2': return 53;
    default: return 0;
    }
}
