"""Generate duelClone.ws: a deep copy of a running CBetaGwentDuelSession for AI lookahead.

* Battle classes get `public` fields (the cloner reads/writes them directly) and two
  bookkeeping fields on every root class (bgCloneEpoch/bgCloneRef).
* Re-run after any change of battle class fields:  python tools/ai/gen_clone.py
"""
from pathlib import Path
import re, sys
sys.path.insert(0, str(Path(__file__).parent))
import ws2js, build_js

ROOT = Path(__file__).resolve().parents[2]
CORE = ROOT / 'BetaGwent/scripts/game/betagwent'
DEV = ROOT / 'BetaGwent/development/scripts/game/betagwent'
OUT = DEV / 'duelClone.ws'
MARK = '// BG_CLONE_FIELDS'
SKIP_FIELDS = {('CBetaGwentDuelSession', 'visualFrames')}
SEATS = {'ownerId', 'controllerId', 'ownerPlayerId', 'positionPlayerId', 'playerId',
         'targetPlayerId', 'startingPlayerId', 'currentPlayerId', 'roundStarter',
         'visualSide', 'savedSourceSide', 'side', 'targetSide'}

def battle_files():
    return sorted(CORE.glob('*.ws')) + [DEV / (n + '.ws') for n in build_js.NAMES if (DEV / (n + '.ws')).exists()]

def program():
    files = [f for f in battle_files() if f.name != 'duelClone.ws']
    _, prog = ws2js.build(files, sorted(DEV.glob('*.ws')))
    return prog

def patch_sources(prog):
    roots = {c.name for c in prog.classes.values() if c.base not in prog.classes}
    for f in battle_files():
        if f.name == 'duelClone.ws': continue
        src = open(f, encoding='utf-8-sig', newline='').read(); out = []; last = 0; changed = False
        for block in ws2js.split_blocks(src):
            kw, name = ws2js.head_name(block)
            if kw != 'class' or name not in prog.classes: continue
            a = block[0].pos; b = block[-1].pos + 1
            body = src[a:b]
            nb = re.sub(r'\b(private|protected)(\s+)var\b', r'public\2var', body)
            if name in roots and MARK not in nb:
                brace = nb.index('{')
                nb = nb[:brace + 1] + ('\r\n' if '\r\n' in nb else '\n') + '    ' + MARK + '\n    public var bgCloneEpoch : int; public var bgCloneRef : IScriptable;' + nb[brace + 1:]
            if nb != body:
                out.append(src[last:a]); out.append(nb); last = b; changed = True
        if changed:
            out.append(src[last:])
            open(f, 'w', encoding='utf-8-sig', newline='').write(''.join(out))
            print('patched', f.name)

def chain(prog, c):
    res = []
    while c is not None:
        res.append(c); c = prog.classes.get(c.base)
    return res

def depth(prog, c): return len(chain(prog, c))

def gen(prog):
    P = prog
    classes = sorted(P.classes.values(), key=lambda c: (-depth(P, c), c.name))
    roots = [c for c in P.classes.values() if c.base not in P.classes]
    # Value structs need a recursive copy when they contain references or seat
    # identifiers. Definitions contain relative targetSide masks, not seats.
    transformed = set()
    def needs_transform(sn):
        if sn not in P.structs or sn in ('SBetaGwentDuelDefinition', 'SBetaGwentTemplateHeader'): return False
        if sn in transformed: return True
        for n, raw in P.structs[sn].fields:
            t = P.norm(raw); el = t[1] if isinstance(t, tuple) else t
            if n in SEATS or n in ('winnerMask', 'matchWinnerMask') or el in P.classes or needs_transform(el):
                transformed.add(sn); return True
        return False
    for sn in P.structs: needs_transform(sn)
    def counterpart(n, names):
        other = n[:-3]+'Two' if n.endswith('One') else n[:-3]+'One' if n.endswith('Two') else ''
        return other if other in names else n
    def copy_value(dst, src, t, n):
        if t in P.classes: return f'{dst} = ({t})Obj({src});'
        if t in transformed: return f'{dst} = Struct{t}({src});'
        if t == 'int' and n in SEATS: return f'{dst} = Seat({src});'
        if t == 'int' and n in ('winnerMask', 'matchWinnerMask'): return f'{dst} = Winner({src});'
        return f'{dst} = {src};'
    L = []
    L.append('// Generated by tools/ai/gen_clone.py. Do not edit by hand.')
    L.append('// Deep copy of a duel session for AI lookahead; no visuals are copied.')
    L.append('class CBetaGwentCloner extends IScriptable')
    L.append('{')
    L.append('    private var epoch, head : int;')
    L.append('    private var flipSeats : bool;')
    L.append('    private var originals, copies : array<IScriptable>;')
    L.append('    public function CloneSession(source : CBetaGwentDuelSession, stamp : int, optional reverseSeats : bool) : CBetaGwentDuelSession')
    L.append('    {')
    L.append('        var result : CBetaGwentDuelSession;')
    L.append('        epoch = stamp; head = 0; flipSeats = reverseSeats; originals.Clear(); copies.Clear();')
    L.append('        result = (CBetaGwentDuelSession)Obj(source);')
    L.append('        while (head < originals.Size()) { CopyAny(originals[head], copies[head]); head += 1; }')
    L.append('        return result;')
    L.append('    }')
    L += ['    private function Seat(value : int) : int',
          '    { if (!flipSeats) return value; if (value == 1) return 2; if (value == 2) return 1; return value; }',
          '    private function Winner(value : int) : int',
          '    { if (!flipSeats) return value; return (value & -4) | ((value & 1) * 2) | ((value & 2) / 2); }']
    for sn in sorted(transformed):
        fields = P.structs[sn].fields; names = {n for n,t in fields}
        L += [f'    private function Struct{sn}(src : {sn}) : {sn}', '    {', f'        var dst : {sn};', '        dst = src;']
        for n, raw in fields:
            t=P.norm(raw); other=counterpart(n,names)
            code=copy_value('dst.'+n,'src.'+n,t,n)
            if other!=n: code=f'if (flipSeats) {{ {copy_value("dst."+n,"src."+other,t,n)} }} else {{ {code} }}'
            L.append('        '+code)
        L += ['        return dst;', '    }']
    # Obj
    L.append('    public function Obj(o : IScriptable) : IScriptable')
    L.append('    {')
    L.append('        var n : IScriptable;')
    for i, r in enumerate(roots): L.append(f'        var r{i} : {r.name};')
    L.append('        if (!o) return NULL;')
    for i, r in enumerate(roots):
        L.append(f'        r{i} = ({r.name})o;')
        L.append(f'        if (r{i}) {{ if (r{i}.bgCloneEpoch == epoch) return r{i}.bgCloneRef; n = Make(o); r{i}.bgCloneEpoch = epoch; r{i}.bgCloneRef = n; originals.PushBack(o); copies.PushBack(n); return n; }}')
    L.append('        return NULL;')
    L.append('    }')
    # Make
    L.append('    private function Make(o : IScriptable) : IScriptable')
    L.append('    {')
    for c in classes:
        if c.abstract: continue
        L.append(f'        if (({c.name})o) return new {c.name} in this;')
    L.append('        return NULL;')
    L.append('    }')
    # CopyAny
    L.append('    private function CopyAny(src : IScriptable, dst : IScriptable)')
    L.append('    {')
    for c in classes:
        if c.abstract: continue
        L.append(f'        if (({c.name})src) {{ Copy{c.name[len("CBetaGwent"):] if c.name.startswith("CBetaGwent") else c.name}(({c.name})src, ({c.name})dst); return; }}')
    L.append('    }')
    # per-class copy
    for c in classes:
        if c.abstract: continue
        short = c.name[len('CBetaGwent'):] if c.name.startswith('CBetaGwent') else c.name
        fields = []
        for k in reversed(chain(P, c)):
            for n, t in k.fields:
                if n not in ('bgCloneEpoch', 'bgCloneRef'): fields.append((k.name, n, P.norm(t)))
        locs = set(); body = []
        names = {n for owner,n,t in fields}
        for owner, n, t in fields:
            if (owner, n) in SKIP_FIELDS or (c.name, n) in SKIP_FIELDS:
                body.append(f'        dst.{n}.Clear();'); continue
            other=counterpart(n,names)
            source=n
            if other!=n:
                body.append(f'        if (flipSeats) {{ {copy_value("dst."+n,"src."+other,t,n)} }} else {{ {copy_value("dst."+n,"src."+n,t,n)} }}' if not isinstance(t,tuple) else f'        if (flipSeats) dst.{n} = src.{other}; else dst.{n} = src.{n};')
                source=None # paired arrays are transformed from the copied value
                if not isinstance(t,tuple): continue
            if isinstance(t, tuple):
                el = t[1]
                if el in P.classes:
                    locs.add('i')
                    if source: body.append(f'        dst.{n} = src.{n};')
                    body.append(f'        for (i = 0; i < dst.{n}.Size(); i += 1) dst.{n}[i] = ({el})Obj(dst.{n}[i]);')
                elif el in transformed:
                    locs.add('i')
                    if source: body.append(f'        dst.{n} = src.{n};')
                    body.append(f'        for (i = 0; i < dst.{n}.Size(); i += 1) dst.{n}[i] = Struct{el}(dst.{n}[i]);')
                elif isinstance(el, tuple):
                    raise ValueError('nested arrays unsupported: %s.%s' % (c.name, n))
                else:
                    if source: body.append(f'        dst.{n} = src.{n};')
            else:
                body.append('        '+copy_value('dst.'+n,'src.'+n,t,n))
        if c.name=='CBetaGwentDuelWeather':
            locs.add('i');locs.add('swap')
            body += ['        if (flipSeats) {',
                     '            for (i = 0; i < 3 && i + 3 < dst.hazards.Size(); i += 1) { swap = dst.hazards[i]; dst.hazards[i] = dst.hazards[i+3]; dst.hazards[i+3] = swap; }',
                     '            for (i = 0; i < dst.dreamRows.Size(); i += 1) dst.dreamRows[i] = (dst.dreamRows[i]+3)%6;', '        }']
        L.append(f'    private function Copy{short}(src : {c.name}, dst : {c.name})')
        L.append('    {')
        decl = []
        if 'i' in locs: decl.append('        var i : int;')
        if 'swap' in locs: decl.append('        var swap : int;')
        for l in sorted(locs):
            if l.startswith('slot'): decl.append(f'        var {l} : {l[4:]};')
        L += decl + body
        L.append('    }')
    L.append('}')
    OUT.write_text('﻿' + '\n'.join(L) + '\n', encoding='utf-8')
    print('wrote', OUT, len(L), 'lines')

if __name__ == '__main__':
    prog = program()
    patch_sources(prog)
    prog = program()
    gen(prog)
