"""Build duelAIWorth.ws from self-play statistics (tools/ai/jshost/worth.js outputs)."""
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'BetaGwent/development/scripts/game/betagwent/duelAIWorth.ws'
agg = {}
for f in sys.argv[1:]:
    for t, w in json.load(open(f)).items():
        a = agg.setdefault(int(t), {'n': 0, 'imm': 0, 'grow': 0, 'growN': 0})
        for k in a: a[k] += w[k]
lines = ['﻿// Generated by tools/ai/gen_worth.py from self-play (immediate swing + own growth to round end).',
         'function BetaGwentAICardWorth(templateId : int, fallback : int) : int', '{', '    switch(templateId)', '    {']
for t in sorted(agg):
    a = agg[t]
    if a['n'] < 4: continue
    worth = a['imm'] / a['n'] + (a['grow'] / a['growN'] if a['growN'] >= 3 else 0)
    lines.append(f'    case {t}: return {round(worth)};')
lines += ['    }', '    return fallback;', '}', '']
OUT.write_text('\n'.join(lines), encoding='utf-8')
print('wrote', OUT, sum(1 for l in lines if 'case' in l), 'cards')
