"""Generate manual AI tuning and an ordinary-NPC shuffle bag; no deck import."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def main():
    config=json.loads((ROOT/'data/beta924/ai/tuning95.json').read_text('utf8'))
    rules=json.loads((ROOT/'data/beta924/ai/rules.json').read_text('utf8'))
    reserve=config['leaderReserveByRound'];assert len(reserve)==3 and all(isinstance(v,int) and 0<=v<=40 for v in reserve)
    minimum=config['leaderMinimumAbilityGain'];opening=config['leaderOpeningMinimumAbilityGain'];hand=config['leaderOpeningHandSize']
    assert all(isinstance(v,int) and 0<=v<=40 for v in (minimum,opening,hand))
    overrides=config['leaderMinimumAbilityGainByTemplate'];assert all(str(k).isdigit() and isinstance(v,int) and 0<=v<=40 for k,v in overrides.items())
    assert config['ordinaryPool']=='active_archetypes'
    pool=[p['presetId'] for p in rules['profiles'] if p['active']];assert len(pool)==len(set(pool)) and pool
    lines=['// Generated by tools/build_ai_tuning95.py from data/beta924/ai/tuning95.json.',
      'function BetaGwentAILeaderReserve(round : int) : int {',
      f'    if(round<=1)return {reserve[0]};if(round==2)return {reserve[1]};return {reserve[2]};','}',
      'function BetaGwentAILeaderAbilityMinimum(templateId : int) : int {','    switch(templateId) {']
    lines += [f'    case {k}: return {v};' for k,v in overrides.items()]
    lines += [f'    default:return {minimum};','    }','}',
      'function BetaGwentAILeaderUseful(templateId : int, round : int, ownHand : int, body : int, gain : int, setup : int, enemyPassed : bool, deficit : int) : bool {',
      '    if(gain<=0)return false;',
      '    if(enemyPassed && gain>=Max(1,deficit))return true;',
      '    if(ownHand==0 || round>=3)return true;',
      '    if(setup>0 && !enemyPassed)return true;',
      '    if(gain-body<BetaGwentAILeaderAbilityMinimum(templateId))return false;',
      f'    if(round==1 && ownHand>={hand} && !enemyPassed && gain-body<{opening})return false;',
      '    return true;','}',
      'function BetaGwentAIOrdinaryPresets(out ids : array<int>) {','    ids.Clear();']
    lines += [f'    ids.PushBack({i});' for i in pool]
    lines += ['}',
      'function BetaGwentAIChooseOrdinaryPreset() : int {',
      '    var manager : CR4GwintManager;var i,j,tmp,picked : int;',
      '    manager=theGame.GetGwintManager();if(!manager)return 54;',
      '    if(manager.betaOrdinaryDeckBag.Size()==0) {',
      '        BetaGwentAIOrdinaryPresets(manager.betaOrdinaryDeckBag);',
      '        for(i=manager.betaOrdinaryDeckBag.Size()-1;i>0;i-=1){',
      '            j=RandRange(i+1);tmp=manager.betaOrdinaryDeckBag[i];',
      '            manager.betaOrdinaryDeckBag[i]=manager.betaOrdinaryDeckBag[j];manager.betaOrdinaryDeckBag[j]=tmp;',
      '        }',
      '        i=manager.betaOrdinaryDeckBag.Size()-1;',
      '        if(i>0 && manager.betaOrdinaryDeckBag[i]==manager.betaOrdinaryLastPreset){',
      '            tmp=manager.betaOrdinaryDeckBag[0];manager.betaOrdinaryDeckBag[0]=manager.betaOrdinaryDeckBag[i];manager.betaOrdinaryDeckBag[i]=tmp;',
      '        }',
      '    }',
      '    i=manager.betaOrdinaryDeckBag.Size()-1;picked=manager.betaOrdinaryDeckBag[i];manager.betaOrdinaryDeckBag.Erase(i);',
      '    manager.betaOrdinaryLastPreset=picked;',
      '    LogChannel(\'BetaGwent\',"DUEL_AI_POOL preset="+picked+" remaining="+manager.betaOrdinaryDeckBag.Size()+" policy=shuffle95");',
      '    return picked;','}']
    (ROOT/'BetaGwent/development/scripts/game/betagwent/duelAITuning.ws').write_text('\n'.join(lines)+'\n','utf-8-sig')
    print('Generated tuning and shuffle pool:',len(pool),'archetypes')
if __name__=='__main__':main()
